name: swiftest-env

channels:
  - conda-forge
  - defaults

dependencies:
  - python>=3.10
  - xarray>=2024.10.0
  - scipy
  - h5py
  - h5netcdf
  - dask
  - distributed
  - bottleneck
  - matplotlib
  - astropy>=6
  - astroquery
  - tqdm
  - x264>=1!157.20191217
  - ffmpeg>=4.3.2
  - cython>=3
  - pkg-config
  - meson-python>=0.14
  - setuptools_scm>=8
  - fftw>=3.3.8
  - blas-devel>=3.8
  - cartopy>=0.18.0
  - gmt>=6.1.1
  - pygmt>=0.3.0
  - ducc0>=0.15
  - palettable>=3.3
  - jupyter
  - pip
  - flake8
  - pyshtools
  - scikit-build-core
  - ipykernel
