swiftest_driver – swiftest
swiftest_driver Program
David A. Minton
74 statements
Source File
Uses
swiftest
Driver program for the Swiftest integrators. Unlike the earlier Swift and Swifter drivers, in Swiftest all integrators are run from this single program.
Adapted from Swifter by David E. Kaufmann's Swifter driver programs swifter_[bs,helio,ra15,rmvs,symba,tu4,whm].f90 Adapted from Hal Levison and Martin Duncan's Swift driver programs Read in the user-defined parameters file and the initial conditions of the system Define the maximum number of threads
Step the system forward in time
Evaluate any discards or collisional outcomes
If the loop counter is at the output cadence value, append the data file with a single frame If the loop counter is at the dump cadence value, dump the state of the system to a file in case it needs to be restarted
Calls
Contents
Variables
nbody_system param integrator param_file_name ierr iloop idump iout ioutput_t0 nloops old_t_final timer
Variables
Type Attributes Name Initial
class(swiftest_nbody_system), allocatable :: nbody_system
Polymorphic object containing the nbody system to be integrated
class(swiftest_parameters), allocatable :: param
Run configuration parameters
integer(kind=I4B) :: integrator
Integrator type code (see swiftest_globals for symbolic names)
character(len=:), allocatable :: param_file_name
Name of the file containing user-defined parameters
integer(kind=I4B) :: ierr
I/O error code
integer(kind=I8B) :: iloop
Loop counter
integer(kind=I8B) :: idump
Dump cadence counter
integer(kind=I8B) :: iout
Output cadence counter
integer(kind=I8B) :: ioutput_t0
The output frame counter at time 0
integer(kind=I8B) :: nloops
Number of steps to take in the simulation
real(kind=DP) :: old_t_final = 0.0_DP
Output time at which writing should start, in order to prevent duplicate lines being written for restarts
type(walltimer) :: timer
Object used for computing elapsed wall time
Call graph
swiftest_driver calls setup_construct_system, io_get_args, util_exit