swiftest_symba – swiftest
swiftest_symba Program
The Purdue Swiftest Team - David A. Minton, Carlisle A. Wishard, Jennifer L.L. Pouplin, and Jacob R. Elliott
243 statements
Source File
Uses
io
swiftest
module_swiftest
module_symba
module_interfaces
module_swiftestalloc
Driver program for the Symplectic Massive Body Algorithm
Adapted from Swifter by David E. Kaufmanna swiftert_symba.f90 Adapted from Hal Levison and Martin Duncan's Swift program swift_symba5.f Reference: Duncan, M. J., Levison, H. F. & Lee, M. H. 1998. Astron. J., 116, 2067. The following are temporary until the conversion to the new module structure is complete
Calls
Contents
Variables
param feature nplmax ntpmax istep_out istep_dump t0 tstop dt j2rp2 j4rp4 rmin rmax rmaxu qmin qmin_alo qmin_ahi qmin_coord encounter_file inplfile intpfile in_type outfile out_type out_form out_stat ierr lfirst lfrag_add npl ntp ntp0 nsppl nsptp iout idump iloop nplplenc npltpenc nmergeadd nmergesub fragmax t tfrac tbase mtiny ke pe te eoffset htot inparfile symba_plA symba_tpA discard_tpA discard_plA plplenc_list pltpenc_list mergeadd_list mergesub_list egyiu start finish
Variables
Type Attributes Name Initial
type(input_parameters) :: param
type(feature_list) :: feature
integer(kind=I4B) :: nplmax
integer(kind=I4B) :: ntpmax
integer(kind=I4B) :: istep_out
integer(kind=I4B) :: istep_dump
real(kind=DP) :: t0
real(kind=DP) :: tstop
real(kind=DP) :: dt
real(kind=DP) :: j2rp2
real(kind=DP) :: j4rp4
real(kind=DP) :: rmin
real(kind=DP) :: rmax
real(kind=DP) :: rmaxu
real(kind=DP) :: qmin
real(kind=DP) :: qmin_alo
real(kind=DP) :: qmin_ahi
character(len=strmax) :: qmin_coord
character(len=strmax) :: encounter_file
character(len=strmax) :: inplfile
character(len=strmax) :: intpfile
character(len=strmax) :: in_type
character(len=strmax) :: outfile
character(len=strmax) :: out_type
character(len=strmax) :: out_form
character(len=strmax) :: out_stat
integer(kind=I4B) :: ierr
Error code
logical :: lfirst
logical :: lfrag_add
integer(kind=I4B) :: npl
integer(kind=I4B) :: ntp
integer(kind=I4B) :: ntp0
integer(kind=I4B) :: nsppl
integer(kind=I4B) :: nsptp
integer(kind=I4B) :: iout
integer(kind=I4B) :: idump
integer(kind=I4B) :: iloop
integer(kind=I4B) :: nplplenc
integer(kind=I4B) :: npltpenc
integer(kind=I4B) :: nmergeadd
integer(kind=I4B) :: nmergesub
integer(kind=I4B) :: fragmax
real(kind=DP) :: t
real(kind=DP) :: tfrac
real(kind=DP) :: tbase
real(kind=DP) :: mtiny
real(kind=DP) :: ke
real(kind=DP) :: pe
real(kind=DP) :: te
real(kind=DP) :: eoffset
real(kind=DP), dimension(ndim) :: htot
character(len=strmax) :: inparfile
type(symba_pl) :: symba_plA
type(symba_tp) :: symba_tpA
type(swiftest_tp) :: discard_tpA
type(swiftest_pl) :: discard_plA
type(symba_plplenc) :: plplenc_list
type(symba_pltpenc) :: pltpenc_list
type(symba_merger) :: mergeadd_list
type(symba_merger) :: mergesub_list
integer(kind=I4B), parameter :: egyiu = 72
real(kind=DP) :: start
real(kind=DP) :: finish
Call graph
swiftest_symba calls symba_tp_deallocate, io_discard_write_symba, symba_merger_deallocate, symba_pl_allocate, symba_energy, util_exit, io_getn, symba_discard_pl, symba_plplenc_allocate, io_write_frame, symba_pltpenc_allocate, symba_step, symba_tp_allocate, symba_pl_deallocate, symba_discard_tp, 7, symba_rearray, util_valid, symba_merger_allocate, util_version, symba_reorder_pl, python_io_write_frame_pl, io_dump_param, io_read_param_in, io_read_pl_in, symba_discard_merge_pl, io_init_tp, io_dump_pl, symba_plplenc_deallocate, symba_pltpenc_deallocate
symba_pl_allocate calls helio_pl_allocate
symba_tp_allocate calls helio_tp_allocate
symba_pl_deallocate calls helio_pl_deallocate
io_read_param_in calls io_read_param_in, util_exit, io_get_token, util_toupper
io_read_pl_in calls io_read_pl_in
helio_pl_allocate calls swiftest_pl_allocate
helio_tp_allocate calls swiftest_tp_allocate
helio_pl_deallocate calls swiftest_pl_deallocate
io_get_token calls io_get_token