swiftest_symba_omp – swiftest
swiftest_symba_omp Program
213 statements
Source File
Uses
module_parameters
module_swiftest
module_symba
module_interfaces
module_swiftestalloc
Calls
Contents
Variables
feature nplmax ntpmax istep_out istep_dump t0 tstop dt j2rp2 j4rp4 rmin rmax rmaxu qmin qmin_alo qmin_ahi qmin_coord encounter_file inplfile intpfile in_type outfile out_type out_form out_stat lfirst lfrag_add npl ntp ntp0 nsppl nsptp iout idump iloop nplplenc npltpenc nmergeadd nmergesub fragmax t tfrac tbase mtiny ke pe te eoffset htot inparfile symba_plA symba_tpA discard_tpA discard_plA plplenc_list pltpenc_list mergeadd_list mergesub_list egyiu start finish
Variables
Type Attributes Name Initial
type(feature_list) :: feature
integer(kind=I4B) :: nplmax
integer(kind=I4B) :: ntpmax
integer(kind=I4B) :: istep_out
integer(kind=I4B) :: istep_dump
real(kind=DP) :: t0
real(kind=DP) :: tstop
real(kind=DP) :: dt
real(kind=DP) :: j2rp2
real(kind=DP) :: j4rp4
real(kind=DP) :: rmin
real(kind=DP) :: rmax
real(kind=DP) :: rmaxu
real(kind=DP) :: qmin
real(kind=DP) :: qmin_alo
real(kind=DP) :: qmin_ahi
character(len=STRMAX) :: qmin_coord
character(len=STRMAX) :: encounter_file
character(len=STRMAX) :: inplfile
character(len=STRMAX) :: intpfile
character(len=STRMAX) :: in_type
character(len=STRMAX) :: outfile
character(len=STRMAX) :: out_type
character(len=STRMAX) :: out_form
character(len=STRMAX) :: out_stat
logical(kind=LGT) :: lfirst
logical(kind=LGT) :: lfrag_add
integer(kind=I4B) :: npl
integer(kind=I4B) :: ntp
integer(kind=I4B) :: ntp0
integer(kind=I4B) :: nsppl
integer(kind=I4B) :: nsptp
integer(kind=I4B) :: iout
integer(kind=I4B) :: idump
integer(kind=I4B) :: iloop
integer(kind=I4B) :: nplplenc
integer(kind=I4B) :: npltpenc
integer(kind=I4B) :: nmergeadd
integer(kind=I4B) :: nmergesub
integer(kind=I4B) :: fragmax
real(kind=DP) :: t
real(kind=DP) :: tfrac
real(kind=DP) :: tbase
real(kind=DP) :: mtiny
real(kind=DP) :: ke
real(kind=DP) :: pe
real(kind=DP) :: te
real(kind=DP) :: eoffset
real(kind=DP), DIMENSION(NDIM) :: htot
character(len=STRMAX) :: inparfile
type(symba_pl) :: symba_plA
type(symba_tp) :: symba_tpA
type(swiftest_tp) :: discard_tpA
type(swiftest_pl) :: discard_plA
type(symba_plplenc) :: plplenc_list
type(symba_pltpenc) :: pltpenc_list
type(symba_merger) :: mergeadd_list
type(symba_merger) :: mergesub_list
integer(kind=I4B), parameter :: egyiu = 72
real(kind=DP) :: start
real(kind=DP) :: finish
Call graph
swiftest_symba_omp calls symba_tp_allocate, symba_plplenc_allocate, symba_energy, symba_tp_deallocate, util_exit, io_dump_pl, io_getn, symba_discard_tp, symba_pl_allocate, python_io_write_frame_pl, io_init_pl, 7, symba_merger_deallocate, symba_plplenc_deallocate, io_write_frame, symba_pltpenc_allocate, symba_discard_pl, symba_rearray, symba_step, symba_merger_allocate, io_init_param, io_dump_param, symba_pltpenc_deallocate, io_init_tp, util_valid, symba_discard_merge_pl, symba_reorder_pl, util_version, symba_pl_deallocate, io_discard_write_symba
symba_tp_allocate calls helio_tp_allocate
symba_pl_allocate calls helio_pl_allocate
symba_pl_deallocate calls helio_pl_deallocate
helio_pl_deallocate calls swiftest_pl_deallocate
helio_pl_allocate calls swiftest_pl_allocate
helio_tp_allocate calls swiftest_tp_allocate