tool_encounter_read – swiftest
tool_encounter_read Program
81 statements
Source File
Uses
module_parameters
module_interfaces
io
Calls
Contents
Variables
param feature nplmax ntpmax istep_out istep_dump t0 tstop dt j2rp2 j4rp4 rmin rmax rmaxu qmin qmin_alo qmin_ahi mtiny qmin_coord encounter_file inplfile intpfile in_type outfile out_type out_form out_stat i ierr id1 id2 t mass1 mass2 xh1 xh2 vh1 vh2 inparfile
Variables
Type Attributes Name Initial
type(input_parameters) :: param
type(feature_list) :: feature
integer(kind=I4B) :: nplmax
integer(kind=I4B) :: ntpmax
integer(kind=I4B) :: istep_out
integer(kind=I4B) :: istep_dump
real(kind=DP) :: t0
real(kind=DP) :: tstop
real(kind=DP) :: dt
real(kind=DP) :: j2rp2
real(kind=DP) :: j4rp4
real(kind=DP) :: rmin
real(kind=DP) :: rmax
real(kind=DP) :: rmaxu
real(kind=DP) :: qmin
real(kind=DP) :: qmin_alo
real(kind=DP) :: qmin_ahi
real(kind=DP) :: mtiny
character(len=STRMAX) :: qmin_coord
character(len=STRMAX) :: encounter_file
character(len=STRMAX) :: inplfile
character(len=STRMAX) :: intpfile
character(len=STRMAX) :: in_type
character(len=STRMAX) :: outfile
character(len=STRMAX) :: out_type
character(len=STRMAX) :: out_form
character(len=STRMAX) :: out_stat
integer(kind=I4B) :: i
integer(kind=I4B) :: ierr
integer(kind=I4B) :: id1
integer(kind=I4B) :: id2
real(kind=DP) :: t
real(kind=DP) :: mass1
real(kind=DP) :: mass2
real(kind=DP), DIMENSION(NDIM) :: xh1
real(kind=DP), DIMENSION(NDIM) :: xh2
real(kind=DP), DIMENSION(NDIM) :: vh1
real(kind=DP), DIMENSION(NDIM) :: vh2
character(len=STRMAX) :: inparfile
Call graph
tool_encounter_read calls io_read_encounter, io_read_param_in, util_exit
io_read_param_in calls io_read_param_in, util_exit, io_get_token, util_toupper
io_get_token calls io_get_token