drift_kepu – swiftest
drift_kepu Subroutine
David A. Minton
17 statements
Source File
pure subroutine drift_kepu(dt, r0, mu, alpha, u, fp, c1, c2, c3, iflag)
Solve Kepler's equation in universal variables
Adapted from David E. Kaufmann's Swifter routine: drift_kepu.f90 Adapted from Hal Levison's Swift routine drift_kepu.f
Arguments
Type Intent Optional Attributes Name
real(kind=DP), intent(in) :: dt
real(kind=DP), intent(in) :: r0
real(kind=DP), intent(in) :: mu
real(kind=DP), intent(in) :: alpha
real(kind=DP), intent(in) :: u
real(kind=DP), intent(out) :: fp
real(kind=DP), intent(out) :: c1
real(kind=DP), intent(out) :: c2
real(kind=DP), intent(out) :: c3
integer(kind=I4B), intent(out) :: iflag
Calls
Called by
Contents
None
Call graph
drift_kepu calls drift_kepu_guess, drift_kepu_new, drift_kepu_fchk, drift_kepu_lag
drift_kepu_guess calls drift_kepu_p3solve, orbel_scget
drift_kepu_new calls drift_kepu_stumpff
drift_kepu_fchk calls drift_kepu_stumpff
drift_kepu_lag calls drift_kepu_stumpff
orbel_scget calls orbel_scget
drift_dan calls drift_kepu