drift_dan – swiftest
drift_dan Subroutine
David A. Minton
56 statements
Source File
pure subroutine drift_dan(mu, x0, v0, dt0, iflag)
Perform Kepler drift, solving Kepler's equation in appropriate variables
Adapted from David E. Kaufmann's Swifter routine: drift_dan.f90 Adapted from Hal Levison and Martin Duncan's Swift routine drift_dan.f
Arguments
Type Intent Optional Attributes Name
real(kind=DP), intent(in) :: mu
real(kind=DP), intent(inout), dimension(:) :: x0
real(kind=DP), intent(inout), dimension(:) :: v0
real(kind=DP), intent(in) :: dt0
integer(kind=I4B), intent(out) :: iflag
Calls
Contents
None
Call graph
drift_dan calls drift_kepmd, drift_kepu
drift_kepu calls drift_kepu_guess, drift_kepu_new, drift_kepu_fchk, drift_kepu_lag
drift_kepu_guess calls drift_kepu_p3solve, orbel_scget
drift_kepu_new calls drift_kepu_stumpff
drift_kepu_fchk calls drift_kepu_stumpff
drift_kepu_lag calls drift_kepu_stumpff
orbel_scget calls orbel_scget