fraggle_util_get_energy_momentum – swiftest
fraggle_util_get_energy_momentum Module Subroutine
David A. Minton
53 statements
Source File
module subroutine fraggle_util_get_energy_momentum(self, colliders, system, param, lbefore) Interface →
Calculates total system energy in either the pre-collision outcome state (lbefore = .true.) or the post-collision outcome state (lbefore = .false.) This subrourtine works by building a temporary internal massive body object out of the non-excluded bodies and optionally with fragments appended. This will get passed to the energy calculation subroutine so that energy is computed exactly the same way is it is in the main program. This will temporarily expand the massive body object in a temporary system object called tmpsys to feed it into symba_energy
Arguments
Type Intent Optional Attributes Name
class(fraggle_fragments), intent(inout) :: self
Fraggle fragment system object
class(fraggle_colliders), intent(inout) :: colliders
Fraggle collider system object
class(swiftest_nbody_system), intent(inout) :: system
Swiftest nbody system object
class(swiftest_parameters), intent(in) :: param
Current swiftest run configuration parameters
logical, intent(in) :: lbefore
Flag indicating that this the "before" state of the system, with colliders included and fragments excluded or vice versa
Calls
Called by
Contents
None
Call graph
fraggle_util_get_energy_momentum calls fraggle_util_construct_temporary_system, fraggle_util_add_fragments_to_system, util_exit, fraggle_util_get_energy_momentum
fraggle_util_construct_temporary_system calls fraggle_util_construct_temporary_system, setup_construct_system
fraggle_util_add_fragments_to_system calls fraggle_util_add_fragments_to_system