fraggle_generate_fragments – swiftest
fraggle_generate_fragments Module Subroutine
Jennifer L.L. Pouplin, Carlisle A. Wishard, and David A. Minton
103 statements
Source File
module subroutine fraggle_generate_fragments(self, colliders, system, param, lfailure) Interface →
Uses
ieee_exceptions
Generates a system of fragments in barycentric coordinates that conserves energy and momentum.
Arguments
Type Intent Optional Attributes Name
class(fraggle_fragments), intent(inout) :: self
Fraggle system object the outputs will be the fragmentation
class(fraggle_colliders), intent(inout) :: colliders
Fraggle colliders object containing the two-body equivalent values of the colliding bodies
class(swiftest_nbody_system), intent(inout) :: system
Swiftest nbody system object
class(swiftest_parameters), intent(in) :: param
Current run configuration parameters
logical, intent(out) :: lfailure
Answers the question: Should this have been a merger instead?
Calls
Called by
Contents
None
Call graph
fraggle_generate_fragments calls fraggle_generate_tan_vel, fraggle_generate_pos_vec, fraggle_generate_rad_vel, fraggle_generate_spins, fraggle_io_log_one_message, fraggle_io_log_generate, fraggle_generate_fragments
fraggle_generate_tan_vel calls fraggle_io_log_one_message, util_minimize_bfgs, fraggle_util_vmag_to_vb, lambda_obj
fraggle_generate_pos_vec calls fraggle_util_shift_vector_to_origin
fraggle_generate_rad_vel calls fraggle_io_log_one_message, util_minimize_bfgs, fraggle_util_vmag_to_vb, lambda_obj
fraggle_generate_spins calls fraggle_io_log_one_message
fraggle_io_log_one_message calls fraggle_io_log_one_message
fraggle_io_log_generate calls fraggle_io_log_generate
fraggle_util_shift_vector_to_origin calls fraggle_util_shift_vector_to_origin
fraggle_util_vmag_to_vb calls fraggle_util_vmag_to_vb, fraggle_util_shift_vector_to_origin