helio_step_tp – swiftest
helio_step_tp Subroutine
34 statements
Source File
subroutine helio_step_tp(lfirsttp, lextra_force, t, npl, nplmax, ntp, ntpmax, helio_plA, helio_tpA, j2rp2, j4rp4, dt, xbeg, xend, ptb, pte)
Uses
module_parameters
module_swiftest
module_helio
module_interfaces
Arguments
Type Intent Optional Attributes Name
logical(kind=LGT), intent(inout) :: lfirsttp
logical(kind=LGT), intent(in) :: lextra_force
real(kind=DP), intent(in) :: t
integer(kind=I4B), intent(in) :: npl
integer(kind=I4B), intent(in) :: nplmax
integer(kind=I4B), intent(in) :: ntp
integer(kind=I4B), intent(in) :: ntpmax
type(helio_pl), intent(inout) :: helio_plA
type(helio_tp), intent(inout) :: helio_tpA
real(kind=DP), intent(in) :: j2rp2
real(kind=DP), intent(in) :: j4rp4
real(kind=DP), intent(in) :: dt
real(kind=DP), intent(in), DIMENSION(NDIM, npl) :: xbeg
real(kind=DP), intent(in), DIMENSION(NDIM, npl) :: xend
real(kind=DP), intent(in), DIMENSION(NDIM) :: ptb
real(kind=DP), intent(in), DIMENSION(NDIM) :: pte
Calls
Contents
None
Call graph
helio_step_tp calls coord_vb2vh_tp, helio_kickvb_tp, helio_lindrift_tp, helio_drift_tp, coord_vh2vb_tp, helio_getacch_tp