helio_getacch_tp – swiftest
helio_getacch_tp Subroutine
51 statements
Source File
subroutine helio_getacch_tp(lflag, lextra_force, t, npl, nplmax, ntp, ntpmax, helio_plA, helio_tpA, xh, j2rp2, j4rp4)
Uses
module_parameters
module_swiftest
module_helio
module_interfaces
Arguments
Type Intent Optional Attributes Name
logical(kind=LGT), intent(in) :: lflag
logical(kind=LGT), intent(in) :: lextra_force
real(kind=DP), intent(in) :: t
integer(kind=I4B), intent(in) :: npl
integer(kind=I4B), intent(in) :: nplmax
integer(kind=I4B), intent(in) :: ntp
integer(kind=I4B), intent(in) :: ntpmax
type(helio_pl), intent(inout) :: helio_plA
type(helio_tp), intent(inout) :: helio_tpA
real(kind=DP), intent(in), DIMENSION(NDIM, npl) :: xh
real(kind=DP), intent(in) :: j2rp2
real(kind=DP), intent(in) :: j4rp4
Calls
Contents
None
Call graph
helio_getacch_tp calls obl_acc_tp, obl_acc, helio_getacch_int_tp