helio_tp_allocate – swiftest
helio_tp_allocate Subroutine
11 statements
Source File
public subroutine helio_tp_allocate(helio_tpA, ntp)
Uses
module_parameters
module_helio
Arguments
Type Intent Optional Attributes Name
type(helio_tp), intent(inout) :: helio_tpA
integer(kind=I4B), intent(in) :: ntp
Calls
Called by
Contents
None
Call graph
helio_tp_allocate calls swiftest_tp_allocate
symba_tp_allocate calls helio_tp_allocate
swiftest_symba_omp calls symba_tp_allocate