helio_pl_allocate – swiftest
helio_pl_allocate Subroutine
11 statements
Source File
public subroutine helio_pl_allocate(helio_plA, npl)
Uses
swiftest
module_helio
Arguments
Type Intent Optional Attributes Name
type(helio_pl), intent(inout) :: helio_plA
integer(kind=I4B), intent(in) :: npl
Calls
Called by
Contents
None
Call graph
helio_pl_allocate calls swiftest_pl_allocate
symba_pl_allocate calls helio_pl_allocate
util_resize_pl calls symba_pl_allocate
swiftest_symba calls symba_pl_allocate