helio_step_pl – swiftest
helio_step_pl Subroutine
39 statements
Source File
subroutine helio_step_pl(lfirst, lextra_force, t, npl, nplmax, helio_plA, j2rp2, j4rp4, dt, xbeg, xend, ptb, pte)
Uses
module_parameters
module_swiftest
module_helio
module_interfaces
Arguments
Type Intent Optional Attributes Name
logical(kind=LGT), intent(inout) :: lfirst
logical(kind=LGT), intent(in) :: lextra_force
real(kind=DP), intent(in) :: t
integer(kind=I4B), intent(in) :: npl
integer(kind=I4B), intent(in) :: nplmax
type(helio_pl), intent(inout) :: helio_plA
real(kind=DP), intent(in) :: j2rp2
real(kind=DP), intent(in) :: j4rp4
real(kind=DP), intent(in) :: dt
real(kind=DP), intent(out), DIMENSION(NDIM, npl) :: xbeg
real(kind=DP), intent(out), DIMENSION(NDIM, npl) :: xend
real(kind=DP), intent(out), DIMENSION(NDIM) :: ptb
real(kind=DP), intent(out), DIMENSION(NDIM) :: pte
Calls
Contents
None
Call graph
helio_step_pl calls coord_vh2vb, coord_vb2vh, helio_drift, helio_lindrift, helio_kickvb, helio_getacch