io_dump_base – swiftest
io_dump_base Module Subroutine
David A. Minton
31 statements
Source File
module subroutine io_dump_base(self, param) Interface →
Dump massive body data to files
Adapted from David E. Kaufmann's Swifter routine: io_dump_pl.f90 and io_dump_tp.f90 Adapted from Hal Levison's Swift routine io_dump_pl.f and io_dump_tp.f
Arguments
Type Intent Optional Attributes Name
class(swiftest_base), intent(inout) :: self
Swiftest base object
class(swiftest_parameters), intent(inout) :: param
Current run configuration parameters
Calls
Called by
Contents
None
Call graph
io_dump_base calls io_write_frame_cb, io_write_frame_body, util_exit, io_dump_base
io_write_frame_cb calls io_write_frame_cb, util_exit
io_write_frame_body calls io_write_frame_body, util_exit
util_exit calls util_exit