io_dump_tp – swiftest
io_dump_tp Subroutine
27 statements
Source File
subroutine io_dump_tp(ntp, swiftest_tpA)
Uses
module_parameters
module_swiftest
module_fxdr
module_interfaces
Arguments
Type Intent Optional Attributes Name
integer(kind=I4B), intent(in) :: ntp
type(swiftest_tp), intent(inout) :: swiftest_tpA
Calls
Contents
None
Call graph
io_dump_tp calls ixdrint, ixdrclose, util_exit, ixdrdmat, dump_tp_file