io_dump_param – swiftest
io_dump_param Subroutine
139 statements
Source File
subroutine io_dump_param(nplmax, ntpmax, ntp, t, tstop, dt, in_type, istep_out, outfile, out_type, out_form, istep_dump, j2rp2, j4rp4, rmin, rmax, rmaxu, qmin, qmin_coord, qmin_alo, qmin_ahi, encounter_file, mtiny, feature, ring_outfile)
Uses
module_parameters
module_interfaces
Arguments
Type Intent Optional Attributes Name
integer(kind=I4B), intent(in) :: nplmax
integer(kind=I4B), intent(in) :: ntpmax
integer(kind=I4B), intent(in) :: ntp
real(kind=DP), intent(in) :: t
real(kind=DP), intent(in) :: tstop
real(kind=DP), intent(in) :: dt
character(len=*), intent(in) :: in_type
integer(kind=I4B), intent(in) :: istep_out
character(len=*), intent(in) :: outfile
character(len=*), intent(in) :: out_type
character(len=*), intent(in) :: out_form
integer(kind=I4B), intent(in) :: istep_dump
real(kind=DP), intent(in) :: j2rp2
real(kind=DP), intent(in) :: j4rp4
real(kind=DP), intent(in) :: rmin
real(kind=DP), intent(in) :: rmax
real(kind=DP), intent(in) :: rmaxu
real(kind=DP), intent(in) :: qmin
character(len=*), intent(in) :: qmin_coord
real(kind=DP), intent(in) :: qmin_alo
real(kind=DP), intent(in) :: qmin_ahi
character(len=*), intent(in) :: encounter_file
real(kind=DP), intent(out), optional :: mtiny
type(feature_list), intent(out) :: feature
character(len=*), intent(out), optional :: ring_outfile
Calls
Contents
None
Call graph
io_dump_param calls dump_pl_file, dump_tp_file, dump_param_file