io_dump_system – swiftest
io_dump_system Module Subroutine
David A. Minton
44 statements
Source File
module subroutine io_dump_system(self, param) Interface →
Dumps the state of the system to files in case the simulation is interrupted. As a safety mechanism, there are two dump files that are written in alternating order so that if a dump file gets corrupted during writing, the user can restart from the older one.
Arguments
Type Intent Optional Attributes Name
class(swiftest_nbody_system), intent(inout) :: self
Swiftest system object
class(swiftest_parameters), intent(inout) :: param
Current run configuration parameters
Calls
Called by
Contents
None
Call graph
io_dump_system calls dump_param_file, dump_cb_file, dump_pl_file, dump_tp_file, io_dump_system