io_discard_write_symba – swiftest
io_discard_write_symba Subroutine
75 statements
Source File
subroutine io_discard_write_symba(t, mtiny, npl, ntp, nsppl, nsptp, nmergeadd, symba_plA, discard_plA, discard_tpA, mergeadd_list, mergesub_list, fname, lbig_discard)
Uses
module_parameters
module_swiftest
module_symba
module_interfaces
Arguments
Type Intent Optional Attributes Name
real(kind=DP), intent(in) :: t
real(kind=DP), intent(in) :: mtiny
integer(kind=I4B), intent(in) :: npl
integer(kind=I4B), intent(in) :: ntp
integer(kind=I4B), intent(in) :: nsppl
integer(kind=I4B), intent(in) :: nsptp
integer(kind=I4B), intent(in) :: nmergeadd
type(symba_pl), intent(inout) :: symba_plA
type(swiftest_pl), intent(inout) :: discard_plA
type(swiftest_tp), intent(inout) :: discard_tpA
type(symba_merger), intent(inout) :: mergeadd_list
type(symba_merger), intent(inout) :: mergesub_list
character(len=*), intent(in) :: fname
logical(kind=LGT), intent(in) :: lbig_discard
Calls
Contents
None
Call graph
io_discard_write_symba calls 3, 2, io_open, util_exit