io_dump_pl – swiftest
io_dump_pl Subroutine
35 statements
Source File
subroutine io_dump_pl(npl, swiftest_plA, lclose, lrhill_present)
Uses
module_parameters
module_swiftest
module_fxdr
module_interfaces
Arguments
Type Intent Optional Attributes Name
integer(kind=I4B), intent(in) :: npl
type(swiftest_pl), intent(inout) :: swiftest_plA
logical(kind=LGT), intent(in) :: lclose
logical(kind=LGT), intent(in) :: lrhill_present
Calls
Contents
None
Call graph
io_dump_pl calls ixdrdouble, dump_pl_file, ixdrclose, util_exit, ixdrint, ixdrdmat