io_get_token – swiftest
io_get_token Subroutine
31 statements
Source File
subroutine io_get_token(buffer, ilength, ifirst, ilast, ierr)
Uses
module_parameters
module_interfaces
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: buffer
integer(kind=I4B), intent(in) :: ilength
integer(kind=I4B), intent(inout) :: ifirst
integer(kind=I4B), intent(out) :: ilast
integer(kind=I4B), intent(out) :: ierr
Called by
Contents
None
Call graph
io_read_param_in calls io_get_token, io_read_param_in
swiftest_symba calls io_read_param_in