io_getn – swiftest
io_getn Subroutine
58 statements
Source File
subroutine io_getn(inplfile, intpfile, in_type, npl, nplmax, ntp, ntpmax)
Uses
module_parameters
module_fxdr
module_interfaces
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: inplfile
character(len=*), intent(in) :: intpfile
character(len=*), intent(in) :: in_type
integer(kind=I4B), intent(out) :: npl
integer(kind=I4B), intent(inout) :: nplmax
integer(kind=I4B), intent(out) :: ntp
integer(kind=I4B), intent(inout) :: ntpmax
Calls
Contents
None
Call graph
io_getn calls io_open_fxdr, io_open, ixdrclose, util_exit, ixdrint