io_init_param – swiftest
io_init_param Subroutine
447 statements
Source File
subroutine io_init_param(inparfile, nplmax, ntpmax, t0, tstop, dt, inplfile, intpfile, in_type, istep_out, outfile, out_type, out_form, out_stat, istep_dump, j2rp2, j4rp4, rmin, rmax, rmaxu, qmin, qmin_coord, qmin_alo, qmin_ahi, encounter_file, mtiny, feature, ring_outfile)
Uses
module_parameters
module_interfaces
Define the maximum number of threads
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: inparfile
integer(kind=I4B), intent(out) :: nplmax
integer(kind=I4B), intent(out) :: ntpmax
real(kind=DP), intent(out) :: t0
real(kind=DP), intent(out) :: tstop
real(kind=DP), intent(out) :: dt
character(len=*), intent(out) :: inplfile
character(len=*), intent(out) :: intpfile
character(len=*), intent(out) :: in_type
integer(kind=I4B), intent(out) :: istep_out
character(len=*), intent(out) :: outfile
character(len=*), intent(out) :: out_type
character(len=*), intent(out) :: out_form
character(len=*), intent(out) :: out_stat
integer(kind=I4B), intent(out) :: istep_dump
real(kind=DP), intent(out) :: j2rp2
real(kind=DP), intent(out) :: j4rp4
real(kind=DP), intent(out) :: rmin
real(kind=DP), intent(out) :: rmax
real(kind=DP), intent(out) :: rmaxu
real(kind=DP), intent(out) :: qmin
character(len=*), intent(out) :: qmin_coord
real(kind=DP), intent(out) :: qmin_alo
real(kind=DP), intent(out) :: qmin_ahi
character(len=*), intent(out) :: encounter_file
real(kind=DP), intent(out), optional :: mtiny
type(feature_list), intent(out) :: feature
character(len=*), intent(out), optional :: ring_outfile
Calls
Contents
None
Call graph
io_init_param calls util_toupper, io_open, util_exit, io_get_token