io_init_tp – swiftest
io_init_tp Subroutine
37 statements
Source File
subroutine io_init_tp(intpfile, in_type, ntp, symba_tpA)
Uses
module_parameters
module_symba
module_helio
module_swiftest
module_fxdr
module_interfaces
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: intpfile
character(len=*), intent(in) :: in_type
integer(kind=I4B), intent(in) :: ntp
type(symba_tp), intent(inout) :: symba_tpA
Calls
Contents
None
Call graph
io_init_tp calls ixdrint, ixdrdmat, io_open_fxdr, ixdrclose, io_open