io_init_pl – swiftest
io_init_pl Subroutine
91 statements
Source File
subroutine io_init_pl(inplfile, in_type, lclose, lrhill_present, npl, symba_plA)
Uses
module_parameters
module_symba
module_helio
module_swiftest
module_fxdr
module_interfaces
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: inplfile
character(len=*), intent(in) :: in_type
logical(kind=LGT), intent(in) :: lclose
logical(kind=LGT), intent(in) :: lrhill_present
integer(kind=I4B), intent(in) :: npl
type(symba_pl), intent(inout) :: symba_plA
Calls
Contents
None
Call graph
io_init_pl calls io_open_fxdr, ixdrdmat, ixdrdouble, io_open, ixdrclose, util_exit, ixdrint