io_param_reader – swiftest
io_param_reader Module Subroutine
The Purdue Swiftest Team - David A. Minton, Carlisle A. Wishard, Jennifer L.L. Pouplin, and Jacob R. Elliott
320 statements
Source File
module subroutine io_param_reader(self, unit, iotype, v_list, iostat, iomsg) Interface →
Read in parameters for the integration Currently this procedure does not work in user-defined derived-type input mode e.g. read(unit,'(DT)') param as the newline characters are ignored in the input file when compiled in ifort.
Adapted from David E. Kaufmann's Swifter routine io_init_param.f90 Adapted from Martin Duncan's Swift routine io_init_param.f Do basic sanity checks on the input values
Arguments
Type Intent Optional Attributes Name
class(swiftest_parameters), intent(inout) :: self
Collection of parameters
integer, intent(in) :: unit
File unit number
character(len=*), intent(in) :: iotype
Dummy argument passed to the input/output procedure contains the text from the char-literal-constant, prefixed with DT. If you do not include a char-literal-constant, the iotype argument contains only DT.
integer, intent(in) :: v_list(:)
The first element passes the integrator code to the reader
integer, intent(out) :: iostat
IO status code
character(len=*), intent(inout) :: iomsg
Message to pass if iostat /= 0
Calls
Called by
Contents
None
Call graph
io_param_reader calls io_get_token, io_toupper, io_param_reader
io_get_token calls io_get_token
io_toupper calls io_toupper