io_read_hdr – swiftest
io_read_hdr Function
46 statements
Source File
function io_read_hdr(iu, t, npl, ntp, iout_form, out_type)
Uses
module_parameters
module_fxdr
module_interfaces
Arguments
Type Intent Optional Attributes Name
integer(kind=I4B), intent(in) :: iu
real(kind=DP), intent(out) :: t
integer(kind=I4B), intent(out) :: npl
integer(kind=I4B), intent(out) :: ntp
integer(kind=I4B), intent(out) :: iout_form
character(len=*), intent(in) :: out_type
Return Value integer(kind=I4B)
Calls
Contents
None
Call graph
io_read_hdr calls ixdrimat, ixdrdouble, ixdrreal