io_read_param_in – swiftest
io_read_param_in Module Procedure
David A. Minton
251 statements
Source File
module procedure io_read_param_in module function io_read_param_in(inparfile) result(param) Interface →
Read in parameters for the integration beginning with or containing "!". If "!" is present, any remaining part of the buffer including the "!" is ignored
Adapted from Swifter io_init_param Original author David E. Kaufmann
Define the maximum number of threads
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: inparfile
Return Value type(input_parameters)
Calls
Called by
Contents
None
Call graph
io_read_param_in calls util_exit, io_get_token, util_toupper, io_read_param_in
io_get_token calls io_get_token
swiftest_symba calls io_read_param_in
tool_encounter_read calls io_read_param_in