io_write_hdr – swiftest
io_write_hdr Subroutine
59 statements
Source File
subroutine io_write_hdr(iu, t, npl, ntp, iout_form, out_type)
Uses
swiftest
module_fxdr
module_interfaces
Arguments
Type Intent Optional Attributes Name
integer(kind=I4B), intent(in) :: iu
real(kind=DP), intent(in) :: t
integer(kind=I4B), intent(in) :: npl
integer(kind=I4B), intent(in) :: ntp
integer(kind=I4B), intent(in) :: iout_form
character(len=*), intent(in) :: out_type
Calls
Contents
None
Call graph
io_write_hdr calls ixdrreal, ixdrimat, util_exit, ixdrdouble