io_write_encounter – swiftest
io_write_encounter Subroutine
63 statements
Source File
subroutine io_write_encounter(t, name1, name2, mass1, mass2, radius1, radius2, xh1, xh2, vh1, vh2, encounter_file, out_type)
Uses
module_parameters
module_fxdr
module_interfaces
Arguments
Type Intent Optional Attributes Name
real(kind=DP), intent(in) :: t
integer(kind=I4B), intent(in) :: name1
integer(kind=I4B), intent(in) :: name2
real(kind=DP), intent(in) :: mass1
real(kind=DP), intent(in) :: mass2
real(kind=DP), intent(in) :: radius1
real(kind=DP), intent(in) :: radius2
real(kind=DP), intent(in), DIMENSION(NDIM) :: xh1
real(kind=DP), intent(in), DIMENSION(NDIM) :: xh2
real(kind=DP), intent(in), DIMENSION(NDIM) :: vh1
real(kind=DP), intent(in), DIMENSION(NDIM) :: vh2
character(len=*), intent(in) :: encounter_file
character(len=*), intent(in) :: out_type
Calls
Contents
None
Call graph
io_write_encounter calls io_open_fxdr, io_open, util_exit, ixdrdouble, ixdrclose