io_write_frame – swiftest
io_write_frame Subroutine
118 statements
Source File
subroutine io_write_frame(t, npl, ntp, swiftest_plA, swiftest_tpA, outfile, out_type, out_form, out_stat)
Uses
module_parameters
module_swiftest
module_fxdr
module_interfaces
Arguments
Type Intent Optional Attributes Name
real(kind=DP), intent(in) :: t
integer(kind=I4B), intent(in) :: npl
integer(kind=I4B), intent(in) :: ntp
type(swiftest_pl), intent(inout) :: swiftest_plA
type(swiftest_tp), intent(inout) :: swiftest_tpA
character(len=*), intent(in) :: outfile
character(len=*), intent(in) :: out_type
character(len=*), intent(in) :: out_form
character(len=*), intent(in) :: out_stat
Calls
Contents
None
Call graph
io_write_frame calls io_write_hdr, util_exit, orbel_xv2el, io_open_fxdr, ixdrclose, io_write_line, io_open