netcdf_initialize_output – swiftest
netcdf_initialize_output Module Subroutine
Carlisle A. Wishard, Dana Singh, and David A. Minton
108 statements
Source File
module subroutine netcdf_initialize_output(self, param) Interface →
Uses
ieee_arithmetic
Initialize a NetCDF file system and defines all variables. Create the new output file, deleting any previously existing output file of the same name Define the variables
Arguments
Type Intent Optional Attributes Name
class(netcdf_parameters), intent(inout) :: self
Parameters used to identify a particular NetCDF dataset
class(swiftest_parameters), intent(in) :: param
Current run configuration parameters
Calls
Called by
Contents
None
Call graph
netcdf_initialize_output calls nf90_def_var, nf90_def_dim, nf90_create, nf90_def_var_fill, nf90_inquire, nf90_inquire_variable, netcdf_initialize_output