netcdf_write_hdr_system – swiftest
netcdf_write_hdr_system Module Subroutine
David A. Minton
31 statements
Source File
module subroutine netcdf_write_hdr_system(self, iu, param) Interface →
Writes header information (variables that change with time, but not particle id). This subroutine significantly improves the output over the original binary file, allowing us to track energy, momentum, and other quantities that previously were handled as separate output files.
Arguments
Type Intent Optional Attributes Name
class(swiftest_nbody_system), intent(in) :: self
Swiftest nbody system object
class(netcdf_parameters), intent(inout) :: iu
Parameters used to for writing a NetCDF dataset to file
class(swiftest_parameters), intent(in) :: param
Current run configuration parameters
Calls
Called by
Contents
None
Call graph
netcdf_write_hdr_system calls nf90_set_fill, nf90_put_var, nf90_open, netcdf_write_hdr_system