orbel_el2xv_vec – swiftest
orbel_el2xv_vec Module Subroutine
David A. Minton
13 statements
Source File
module subroutine orbel_el2xv_vec(self, cb) Interface →
A wrapper method that converts all of the orbital element vectors into cartesian position and velocity vectors for a Swiftest body object. This method deallocates all of the orbital elements after it is finished.
Arguments
Type Intent Optional Attributes Name
class(swiftest_body), intent(inout) :: self
Swiftest body object
class(swiftest_cb), intent(inout) :: cb
Swiftest central body objec
Calls
Called by
Contents
None
Call graph
orbel_el2xv_vec calls orbel_el2xv, orbel_el2xv_vec
orbel_el2xv calls orbel_scget, orbel_ehybrid, orbel_fhybrid, orbel_zget, orbel_schget
orbel_scget calls orbel_scget
orbel_ehybrid calls orbel_esolmd, orbel_eget, orbel_ehie
orbel_fhybrid calls orbel_flon, orbel_fget
orbel_flon calls 3
orbel_esolmd calls orbel_scget
orbel_eget calls orbel_scget
orbel_fget calls orbel_schget
orbel_ehie calls orbel_scget