orbel_scget – swiftest
orbel_scget Module Subroutine
David A. Minton
14 statements
Source File
pure module subroutine orbel_scget(angle, sx, cx) Interface →
Efficiently compute the sine and cosine of an input angle Input angle must be in radians
Adapted from David E. Kaufmann's Swifter routine: orbel_scget.f90 Adapted from Hal Levison's Swift routine orbel_scget.f
Arguments
Type Intent Optional Attributes Name
real(kind=DP), intent(in) :: angle
real(kind=DP), intent(out) :: sx
real(kind=DP), intent(out) :: cx
Called by
Contents
None
Call graph
orbel_scget calls orbel_scget
orbel_el2xv calls orbel_scget, orbel_ehybrid
orbel_esolmd calls orbel_scget
orbel_eget calls orbel_scget
drift_kepu_guess calls orbel_scget
orbel_ehie calls orbel_scget
orbel_el2xv_vec calls orbel_el2xv, orbel_el2xv_vec
drift_kepu calls drift_kepu_guess
orbel_ehybrid calls orbel_esolmd, orbel_eget, orbel_ehie
drift_dan calls drift_kepu