orbel_el2xv – swiftest
orbel_el2xv Subroutine
David A. Minton
73 statements
Source File
pure subroutine orbel_el2xv(mu, a, ie, inc, capom, omega, capm, x, v)
Compute osculating orbital elements from relative C)rtesian position and velocity All angular measures are returned in radians If inclination < TINY, longitude of the ascending node is arbitrarily set to 0
  If eccentricity < sqrt(TINY), argument of pericenter is arbitrarily set to 0
  ALGORITHM:  See Fitzpatrick "Principles of Cel. Mech."
Adapted from Martin Duncan's el2xv.f DATE WRITTEN: May 11, 1992. REVISIONS: May 26 - now use better Kepler solver for ellipses and hyperbolae called EHYBRID.F and FHYBRID.F
Arguments
Type Intent Optional Attributes Name
real(kind=DP), intent(in) :: mu
real(kind=DP), intent(in) :: a
real(kind=DP), intent(in) :: ie
real(kind=DP), intent(in) :: inc
real(kind=DP), intent(in) :: capom
real(kind=DP), intent(in) :: omega
real(kind=DP), intent(in) :: capm
real(kind=DP), intent(out), dimension(:) :: x
real(kind=DP), intent(out), dimension(:) :: v
Calls
Called by
Contents
None
Call graph
orbel_el2xv calls orbel_fhybrid, orbel_ehybrid, orbel_schget, orbel_scget, orbel_zget
orbel_fhybrid calls orbel_flon, orbel_fget
orbel_ehybrid calls orbel_esolmd, orbel_ehie, orbel_eget
orbel_scget calls orbel_scget
orbel_esolmd calls orbel_scget
orbel_ehie calls orbel_scget
orbel_flon calls 3
orbel_eget calls orbel_scget
orbel_fget calls orbel_schget
orbel_el2xv_vec calls orbel_el2xv, orbel_el2xv_vec