orbel_schget – swiftest
orbel_schget Subroutine
7 statements
Source File
pure subroutine orbel_schget(angle, shx, chx)
Arguments
Type Intent Optional Attributes Name
real(kind=DP), intent(in) :: angle
real(kind=DP), intent(out) :: shx
real(kind=DP), intent(out) :: chx
Called by
Contents
None
Call graph
orbel_el2xv calls orbel_schget, orbel_fhybrid
orbel_fget calls orbel_schget
orbel_el2xv_vec calls orbel_el2xv, orbel_el2xv_vec
orbel_fhybrid calls orbel_fget