orbel_fhybrid – swiftest
orbel_fhybrid Function
13 statements
Source File
pure function orbel_fhybrid(e, n)
Arguments
Type Intent Optional Attributes Name
real(kind=DP), intent(in) :: e
real(kind=DP), intent(in) :: n
Return Value real(kind=DP)
Calls
Called by
Contents
None
Call graph
orbel_fhybrid calls orbel_fget, orbel_flon
orbel_fget calls orbel_schget
orbel_flon calls 3
orbel_el2xv calls orbel_fhybrid
orbel_el2xv_vec calls orbel_el2xv, orbel_el2xv_vec