rmvs_step_system – swiftest
rmvs_step_system Module Subroutine
David A. Minton
49 statements
Source File
module subroutine rmvs_step_system(self, param, t, dt) Interface →
Step massive bodies and and active test particles ahead in heliocentric coordinates
Adapted from Hal Levison's Swift routine rmvs3_step.f Adapted from David E. Kaufmann's Swifter routine rmvs_step.f90
Arguments
Type Intent Optional Attributes Name
class(rmvs_nbody_system), intent(inout) :: self
RMVS nbody system object
class(swiftest_parameters), intent(inout) :: param
Current run configuration parameters
real(kind=DP), intent(in) :: t
Current simulation time
real(kind=DP), intent(in) :: dt
Current stepsiz
Calls
Called by
Contents
None
Call graph
rmvs_step_system calls rmvs_step_out, rmvs_interp_out, whm_step_system, rmvs_step_system
rmvs_step_out calls rmvs_step_in, rmvs_interp_in
rmvs_interp_out calls util_exit
rmvs_step_in calls rmvs_peri_tp, rmvs_end_planetocentric, rmvs_make_planetocentric
rmvs_interp_in calls util_exit
rmvs_peri_tp calls xpc, vpc