rmvs_step_out – swiftest
rmvs_step_out Subroutine
David A. Minton
45 statements
Source File
subroutine rmvs_step_out(cb, pl, tp, system, param, t, dt)
Step ACTIVE test particles ahead in the outer encounter region, setting up and calling the inner region integration if necessar
Adapted from Hal Levison's Swift routines rmvs3_step_out.f and rmvs3_step_out2.f Adapted from David E. Kaufmann's Swifter routines rmvs_step_out.f90 and rmvs_step_out2.f90
Arguments
Type Intent Optional Attributes Name
class(rmvs_cb), intent(inout) :: cb
RMVS central body object
class(rmvs_pl), intent(inout) :: pl
RMVS massive body object
class(rmvs_tp), intent(inout) :: tp
RMVS test particle object
class(rmvs_nbody_system), intent(inout) :: system
RMVS nbody system object
class(swiftest_parameters), intent(inout) :: param
Current run configuration parameters
real(kind=DP), intent(in) :: t
Current simulation time
real(kind=DP), intent(in) :: dt
Current stepsiz
Calls
Called by
Contents
None
Call graph
rmvs_step_out calls rmvs_interp_in, rmvs_step_in
rmvs_interp_in calls util_exit
rmvs_step_in calls rmvs_end_planetocentric, rmvs_peri_tp, rmvs_make_planetocentric
rmvs_peri_tp calls vpc, xpc
rmvs_step_system calls rmvs_step_out, rmvs_step_system