rmvs_peri_tp – swiftest
rmvs_peri_tp Subroutine
David A. Minton
71 statements
Source File
subroutine rmvs_peri_tp(tp, pl, t, dt, lfirst, inner_index, ipleP, param)
Determine planetocentric pericenter passages for test particles in close encounters with a planet
Adapted from Hal Levison's Swift routine Adapted from Hal Levison's Swift routine util_peri.f Adapted from David E. Kaufmann's Swifter routine rmvs_peri.f90
Arguments
Type Intent Optional Attributes Name
class(rmvs_tp), intent(inout) :: tp
RMVS test particle object (planetocentric)
class(rmvs_pl), intent(inout) :: pl
RMVS massive body object (heliocentric)
real(kind=DP), intent(in) :: t
current time
real(kind=DP), intent(in) :: dt
step size
logical, intent(in) :: lfirst
Logical flag indicating whether current invocation is the first
integer(kind=I4B), intent(in) :: inner_index
Outer substep number within current set
integer(kind=I4B), intent(in) :: ipleP
index of RMVS planet being closely encountered
class(swiftest_parameters), intent(in) :: param
Current run configuration parameters
Calls
Called by
Contents
None
Call graph
rmvs_peri_tp calls xpc, vpc
rmvs_step_in calls rmvs_peri_tp
rmvs_step_out calls rmvs_step_in
rmvs_step_system calls rmvs_step_out, rmvs_step_system