swiftest_pl_allocate – swiftest
swiftest_pl_allocate Subroutine
17 statements
Source File
public subroutine swiftest_pl_allocate(swiftest_plA, npl)
Uses
module_parameters
module_swiftest
Arguments
Type Intent Optional Attributes Name
type(swiftest_pl), intent(inout) :: swiftest_plA
integer(kind=I4B), intent(in) :: npl
Called by
Contents
None
Call graph
helio_pl_allocate calls swiftest_pl_allocate
symba_rearray calls swiftest_pl_allocate
symba_pl_allocate calls helio_pl_allocate
swiftest_symba_omp calls symba_pl_allocate
util_resize_pl calls symba_pl_allocate