symba_util_append_merger – swiftest
symba_util_append_merger Module Subroutine
David A. Minton
26 statements
Source File
module subroutine symba_util_append_merger(self, source, lsource_mask) Interface →
Append components from one massive body object to another. This method will automatically resize the destination body if it is too small
Arguments
Type Intent Optional Attributes Name
class(symba_merger), intent(inout) :: self
SyMBA massive body object
class(swiftest_body), intent(in) :: source
Source object to append
logical, intent(in), dimension(:) :: lsource_mask
Logical mask indicating which elements to append to
Calls
Called by
Contents
None
Call graph
symba_util_append_merger calls util_append, util_exit, symba_util_append_pl, symba_util_append_merger
symba_util_append_pl calls symba_util_append_pl, util_append, util_exit, util_append_pl