symba_caseresolve – swiftest
symba_caseresolve Subroutine
38 statements
Source File
subroutine symba_caseresolve(t, dt, index_enc, nmergeadd, nmergesub, mergeadd_list, mergesub_list, eoffset, vbs, encounter_file, out_type, npl, ntp, symba_plA, symba_tpA, nplplenc, npltpenc, pltpenc_list, plplenc_list, regime, nplmax, ntpmax, fragmax, mres, rres, array_index1_child, array_index2_child, m1, m2, rad1, rad2, x1, x2, v1, v2)
Uses
module_parameters
module_swiftest
module_helio
module_symba
module_interfaces
Arguments
Type Intent Optional Attributes Name
real(kind=DP), intent(in) :: t
real(kind=DP), intent(in) :: dt
integer(kind=I4B), intent(in) :: index_enc
integer(kind=I4B), intent(inout) :: nmergeadd
integer(kind=I4B), intent(inout) :: nmergesub
type(symba_merger), intent(inout) :: mergeadd_list
type(symba_merger), intent(inout) :: mergesub_list
real(kind=DP), intent(inout) :: eoffset
real(kind=DP), intent(in), DIMENSION(NDIM) :: vbs
character(len=*), intent(in) :: encounter_file
character(len=*), intent(in) :: out_type
integer(kind=I4B), intent(inout) :: npl
integer(kind=I4B), intent(inout) :: ntp
type(symba_pl), intent(inout) :: symba_plA
type(symba_tp), intent(inout) :: symba_tpA
integer(kind=I4B), intent(inout) :: nplplenc
integer(kind=I4B), intent(inout) :: npltpenc
type(symba_pltpenc), intent(inout) :: pltpenc_list
type(symba_plplenc), intent(inout) :: plplenc_list
integer(kind=I4B), intent(in) :: regime
integer(kind=I4B), intent(in) :: nplmax
integer(kind=I4B), intent(in) :: ntpmax
integer(kind=I4B), intent(inout) :: fragmax
real(kind=DP), intent(inout), DIMENSION(3) :: mres
real(kind=DP), intent(inout), DIMENSION(3) :: rres
integer(kind=I4B), intent(inout), DIMENSION(npl) :: array_index1_child
integer(kind=I4B), intent(inout), DIMENSION(npl) :: array_index2_child
real(kind=DP), intent(inout) :: m1
real(kind=DP), intent(inout) :: m2
real(kind=DP), intent(inout) :: rad1
real(kind=DP), intent(inout) :: rad2
real(kind=DP), intent(inout), DIMENSION(NDIM) :: x1
real(kind=DP), intent(inout), DIMENSION(NDIM) :: x2
real(kind=DP), intent(inout), DIMENSION(NDIM) :: v1
real(kind=DP), intent(inout), DIMENSION(NDIM) :: v2
Calls
Contents
None
Call graph
symba_caseresolve calls symba_casedisruption, symba_casesupercatastrophic, symba_casemerge, symba_casehitandrun