symba_step_helio_pl – swiftest
symba_step_helio_pl Subroutine
40 statements
Source File
subroutine symba_step_helio_pl(lfirst, lextra_force, t, npl, nplm, nplmax, helio_plA, j2rp2, j4rp4, dt, xbeg, xend, ptb, pte)
Uses
module_parameters
module_swiftest
module_helio
module_symba
module_interfaces
Arguments
Type Intent Optional Attributes Name
logical(kind=LGT), intent(inout) :: lfirst
logical(kind=LGT), intent(in) :: lextra_force
real(kind=DP), intent(in) :: t
integer(kind=I4B), intent(in) :: npl
integer(kind=I4B), intent(in) :: nplm
integer(kind=I4B), intent(in) :: nplmax
type(helio_pl), intent(inout) :: helio_plA
real(kind=DP), intent(in) :: j2rp2
real(kind=DP), intent(in) :: j4rp4
real(kind=DP), intent(in) :: dt
real(kind=DP), intent(out), DIMENSION(NDIM, nplm) :: xbeg
real(kind=DP), intent(out), DIMENSION(NDIM, nplm) :: xend
real(kind=DP), intent(out), DIMENSION(NDIM) :: ptb
real(kind=DP), intent(out), DIMENSION(NDIM) :: pte
Calls
Contents
None
Call graph
symba_step_helio_pl calls coord_vh2vb, helio_kickvb, coord_vb2vh, helio_lindrift, helio_drift, symba_helio_getacch