symba_pl_deallocate – swiftest
symba_pl_deallocate Subroutine
19 statements
Source File
public subroutine symba_pl_deallocate(symba_plA)
Uses
module_parameters
module_symba
Arguments
Type Intent Optional Attributes Name
type(symba_pl), intent(inout) :: symba_plA
Calls
Called by
Contents
None
Call graph
symba_pl_deallocate calls helio_pl_deallocate
helio_pl_deallocate calls swiftest_pl_deallocate
swiftest_symba calls symba_pl_deallocate
util_resize_pl calls symba_pl_deallocate
swiftest_symba_omp calls symba_pl_deallocate