symba_collision_collider_message – swiftest
symba_collision_collider_message Subroutine
David A. Minton
17 statements
Source File
subroutine symba_collision_collider_message(pl, collidx, collider_message)
Prints a nicely formatted message about which bodies collided, including their names and ids. This subroutine appends the body names and ids to an input message.
Arguments
Type Intent Optional Attributes Name
class(swiftest_pl), intent(in) :: pl
Swiftest massive body object
integer(kind=I4B), intent(in), dimension(:) :: collidx
Index of collisional colliders%idx members
character(len=*), intent(inout) :: collider_message
The message to print to the screen.
Called by
Contents
None
Call graph
symba_collision_casehitandrun calls symba_collision_collider_message, symba_collision_casehitandrun
symba_collision_casedisruption calls symba_collision_collider_message, symba_collision_casedisruption
symba_collision_casemerge calls symba_collision_collider_message, symba_collision_casemerge
symba_collision_resolve_mergers calls symba_collision_casemerge, symba_collision_resolve_mergers
symba_collision_resolve_fragmentations calls symba_collision_casedisruption, symba_collision_casehitandrun, symba_collision_casemerge, symba_collision_resolve_fragmentations