symba_rearray – swiftest
symba_rearray Subroutine
170 statements
Source File
subroutine symba_rearray(npl, ntp, nsppl, nsptp, symba_plA, symba_tpA, nmergeadd, mergeadd_list, discard_plA, discard_tpA, feature)
Uses
module_parameters
module_swiftestalloc
module_swiftest
module_helio
module_symba
module_interfaces
Arguments
Type Intent Optional Attributes Name
integer(kind=I4B), intent(inout) :: npl
integer(kind=I4B), intent(inout) :: ntp
integer(kind=I4B), intent(inout) :: nsppl
integer(kind=I4B), intent(inout) :: nsptp
type(symba_pl), intent(inout) :: symba_plA
type(symba_tp), intent(inout) :: symba_tpA
integer(kind=I4B), intent(inout) :: nmergeadd
type(symba_merger), intent(inout) :: mergeadd_list
type(swiftest_pl), intent(inout) :: discard_plA
type(swiftest_tp), intent(inout) :: discard_tpA
type(feature_list), intent(in) :: feature
Calls
Contents
None
Call graph
symba_rearray calls swiftest_pl_allocate, swiftest_tp_allocate, util_resize_pl