symba_step_interp – swiftest
symba_step_interp Subroutine
64 statements
Source File
subroutine symba_step_interp(lextra_force, lclose, t, npl, nplm, nplmax, ntp, ntpmax, symba_plA, symba_tpA, j2rp2, j4rp4, dt, eoffset, nplplenc, npltpenc, plplenc_list, pltpenc_list, nmergeadd, nmergesub, mergeadd_list, mergesub_list, encounter_file, out_type, fragmax, feature)
Uses
module_parameters
module_swiftest
module_helio
module_symba
module_interfaces
Arguments
Type Intent Optional Attributes Name
logical(kind=LGT), intent(in) :: lextra_force
logical(kind=LGT), intent(in) :: lclose
real(kind=DP), intent(in) :: t
integer(kind=I4B), intent(in) :: npl
integer(kind=I4B), intent(in) :: nplm
integer(kind=I4B), intent(in) :: nplmax
integer(kind=I4B), intent(in) :: ntp
integer(kind=I4B), intent(in) :: ntpmax
type(symba_pl), intent(inout) :: symba_plA
type(symba_tp), intent(inout) :: symba_tpA
real(kind=DP), intent(in) :: j2rp2
real(kind=DP), intent(in) :: j4rp4
real(kind=DP), intent(in) :: dt
real(kind=DP), intent(inout) :: eoffset
integer(kind=I4B), intent(in) :: nplplenc
integer(kind=I4B), intent(in) :: npltpenc
type(symba_plplenc), intent(inout) :: plplenc_list
type(symba_pltpenc), intent(inout) :: pltpenc_list
integer(kind=I4B), intent(inout) :: nmergeadd
integer(kind=I4B), intent(inout) :: nmergesub
type(symba_merger), intent(inout) :: mergeadd_list
type(symba_merger), intent(inout) :: mergesub_list
character(len=*), intent(in) :: encounter_file
character(len=*), intent(in) :: out_type
integer(kind=I4B), intent(inout) :: fragmax
type(feature_list), intent(in) :: feature
Calls
Contents
None
Call graph
symba_step_interp calls coord_vh2vb, coord_vb2vh, helio_lindrift_tp, symba_getacch, helio_lindrift, coord_vh2vb_tp, symba_step_recur, symba_helio_drift, helio_kickvb, coord_vb2vh_tp