symba_collision_mergeaddsub – swiftest
symba_collision_mergeaddsub Subroutine
David A. Minton
126 statements
Source File
subroutine symba_collision_mergeaddsub(system, param, colliders, frag, status)
Fills the pl_discards and pl_adds with removed and added bodies
Arguments
Type Intent Optional Attributes Name
class(symba_nbody_system), intent(inout) :: system
SyMBA nbody system object
class(symba_parameters), intent(inout) :: param
Current run configuration parameters with SyMBA additions
class(fraggle_colliders), intent(inout) :: colliders
Fraggle colliders object
class(fraggle_fragments), intent(inout) :: frag
Fraggle fragmentation system object
integer(kind=I4B), intent(in) :: status
Status flag to assign to adds
Calls
Called by
Contents
None
Call graph
symba_collision_mergeaddsub calls fraggle_io_log_pl
symba_collision_casehitandrun calls symba_collision_mergeaddsub, symba_collision_casehitandrun
symba_collision_casedisruption calls symba_collision_mergeaddsub, symba_collision_casedisruption
symba_collision_casemerge calls symba_collision_mergeaddsub, symba_collision_casemerge
symba_collision_resolve_mergers calls symba_collision_casemerge, symba_collision_resolve_mergers
symba_collision_resolve_fragmentations calls symba_collision_casedisruption, symba_collision_casehitandrun, symba_collision_casemerge, symba_collision_resolve_fragmentations