symba_collision_resolve_mergers – swiftest
symba_collision_resolve_mergers Module Subroutine
David A. Minton
34 statements
Source File
module subroutine symba_collision_resolve_mergers(self, system, param) Interface →
Process list of collisions and merge colliding bodies together.
Arguments
Type Intent Optional Attributes Name
class(symba_plplenc), intent(inout) :: self
SyMBA pl-pl encounter list
class(symba_nbody_system), intent(inout) :: system
SyMBA nbody system object
class(symba_parameters), intent(inout) :: param
Current run configuration parameters with SyMBA additions
Calls
Called by
Contents
None
Call graph
symba_collision_resolve_mergers calls idx2, symba_collision_consolidate_colliders, idx1, symba_collision_casemerge, symba_collision_resolve_mergers
symba_collision_consolidate_colliders calls idx_arr, id_arr
symba_collision_casemerge calls symba_collision_casemerge, symba_collision_collider_message, symba_collision_mergeaddsub, fraggle_io_log_one_message
symba_collision_mergeaddsub calls fraggle_io_log_pl