symba_fragmentation_casesupercatastrophic – swiftest
symba_fragmentation_casesupercatastrophic Module Function
Jennifer L.L. Pouplin, Carlisle A. Wishard, and David A. Minton
108 statements
Source File
module function symba_fragmentation_casesupercatastrophic(system, param, family, x, v, mass, radius, L_spin, Ip, mass_res, Qloss) result(status) Interface →
Create the fragments resulting from a supercatastrophic collision
Arguments
Type Intent Optional Attributes Name
class(symba_nbody_system), intent(inout) :: system
SyMBA nbody system object
class(symba_parameters), intent(in) :: param
Current run configuration parameters with SyMBA additions
integer(kind=I4B), intent(in), dimension(:) :: family
List of indices of all bodies inovlved in the collision
real(kind=DP), intent(inout), dimension(:,:) :: x
Input values that represent a 2-body equivalent of a possibly 2+ body collision
real(kind=DP), intent(inout), dimension(:,:) :: v
Input values that represent a 2-body equivalent of a possibly 2+ body collision
real(kind=DP), intent(inout), dimension(:) :: mass
Input values that represent a 2-body equivalent of a possibly 2+ body collision
real(kind=DP), intent(inout), dimension(:) :: radius
Input values that represent a 2-body equivalent of a possibly 2+ body collision
real(kind=DP), intent(inout), dimension(:,:) :: L_spin
Input values that represent a 2-body equivalent of a possibly 2+ body collision
real(kind=DP), intent(inout), dimension(:,:) :: Ip
Input values that represent a 2-body equivalent of a possibly 2+ body collision
real(kind=DP), intent(inout), dimension(:) :: mass_res
The distribution of fragment mass obtained by the regime calculation
real(kind=DP), intent(inout) :: Qloss
Energy lost during collision
Return Value integer(kind=I4B)
Status flag assigned to this outcome
Calls
Called by
Contents
None
Call graph
symba_fragmentation_casesupercatastrophic calls fragmentation_initialize, symba_fragmentation_casesupercatastrophic
symba_collision_resolve_fragmentations calls symba_fragmentation_casesupercatastrophic, symba_collision_resolve_fragmentations