symba_fragmentation_mergeaddsub – swiftest
symba_fragmentation_mergeaddsub Subroutine
David A. Minton
86 statements
Source File
subroutine symba_fragmentation_mergeaddsub(system, param, family, id_frag, Ip_frag, m_frag, rad_frag, xb_frag, vb_frag, rot_frag, status)
Fills the pl_discards and pl_adds with removed and added bodies
Arguments
Type Intent Optional Attributes Name
class(symba_nbody_system), intent(inout) :: system
SyMBA nbody system object
class(symba_parameters), intent(in) :: param
Current run configuration parameters with SyMBA additions
integer(kind=I4B), intent(in), dimension(:) :: family
List of indices of all bodies inovlved in the collision
integer(kind=I4B), intent(in), dimension(:) :: id_frag
List of fragment ids
real(kind=DP), intent(in), dimension(:,:) :: Ip_frag
Fragment rotational inertia vectors
real(kind=DP), intent(in), dimension(:) :: m_frag
Distribution of fragment mass and radii
real(kind=DP), intent(in), dimension(:) :: rad_frag
Distribution of fragment mass and radii
real(kind=DP), intent(in), dimension(:,:) :: xb_frag
Fragment barycentric position, barycentric velocity, and rotation vectors
real(kind=DP), intent(in), dimension(:,:) :: vb_frag
Fragment barycentric position, barycentric velocity, and rotation vectors
real(kind=DP), intent(in), dimension(:,:) :: rot_frag
Fragment barycentric position, barycentric velocity, and rotation vectors
integer(kind=I4B), intent(in) :: status
Status flag to assign to adds
Called by
Contents
None
Call graph
symba_fragmentation_casedisruption calls symba_fragmentation_mergeaddsub, symba_fragmentation_casedisruption
symba_fragmentation_casehitandrun calls symba_fragmentation_mergeaddsub, symba_fragmentation_casehitandrun
symba_fragmentation_casesupercatastrophic calls symba_fragmentation_mergeaddsub, symba_fragmentation_casesupercatastrophic
symba_fragmentation_casemerge calls symba_fragmentation_mergeaddsub, symba_fragmentation_casemerge
symba_collision_resolve_mergers calls symba_fragmentation_casemerge, symba_collision_resolve_mergers
symba_collision_resolve_fragmentations calls symba_fragmentation_casedisruption, symba_fragmentation_casehitandrun, symba_fragmentation_casemerge, symba_fragmentation_casesupercatastrophic, symba_collision_resolve_fragmentations