symba_collision_resolve_fragmentations – swiftest
symba_collision_resolve_fragmentations Module Subroutine
David A. Minton
69 statements
Source File
module subroutine symba_collision_resolve_fragmentations(self, system, param) Interface →
Process list of collisions, determine the collisional regime, and then create fragments.
The collective mass of the parent and its children The collective radius of the parent and its children The position of the parent from inside the step (at collision) The velocity of the parent from inside the step (at collision) The position of the parent from inside the step (at collision) The velocity of the parent from inside the step (at collision) The collective density of the parent and its children Use the positions and velocities of the parents from indside the step (at collision) to calculate the collisional regime
Arguments
Type Intent Optional Attributes Name
class(symba_plplenc), intent(inout) :: self
SyMBA pl-pl encounter list
class(symba_nbody_system), intent(inout) :: system
SyMBA nbody system object
class(symba_parameters), intent(in) :: param
Current run configuration parameters with SyMBA additions
Calls
Called by
Contents
None
Call graph
symba_collision_resolve_fragmentations calls idx2, symba_fragmentation_casesupercatastrophic, symba_collision_consolidate_familes, symba_fragmentation_casemerge, idx1, symba_fragmentation_casehitandrun, util_exit, symba_fragmentation_casedisruption, symba_collision_resolve_fragmentations
symba_fragmentation_casesupercatastrophic calls symba_fragmentation_casesupercatastrophic, fragmentation_initialize, symba_fragmentation_mergeaddsub
symba_collision_consolidate_familes calls id_arr, idx_arr
symba_fragmentation_casemerge calls symba_fragmentation_casemerge, symba_fragmentation_mergeaddsub
symba_fragmentation_casehitandrun calls symba_fragmentation_casehitandrun, fragmentation_initialize, symba_fragmentation_mergeaddsub
symba_fragmentation_casedisruption calls symba_fragmentation_casedisruption, fragmentation_initialize, symba_fragmentation_mergeaddsub