symba_tp_allocate – swiftest
symba_tp_allocate Subroutine
12 statements
Source File
public subroutine symba_tp_allocate(symba_tpA, ntp)
Uses
swiftest
module_symba
Arguments
Type Intent Optional Attributes Name
type(symba_tp), intent(inout) :: symba_tpA
integer(kind=I4B), intent(in) :: ntp
Calls
Called by
Contents
None
Call graph
symba_tp_allocate calls helio_tp_allocate
helio_tp_allocate calls swiftest_tp_allocate
swiftest_symba calls symba_tp_allocate