symba_step_recur – swiftest
symba_step_recur Subroutine
196 statements
Source File
subroutine symba_step_recur(lclose, t, ireci, npl, nplm, ntp, symba_plA, symba_tpA, dt0, eoffset, nplplenc, npltpenc, plplenc_list, pltpenc_list, nmergeadd, nmergesub, mergeadd_list, mergesub_list, encounter_file, out_type, nplmax, ntpmax, fragmax, feature)
Uses
module_parameters
module_swiftest
module_helio
module_symba
module_interfaces
Arguments
Type Intent Optional Attributes Name
logical(kind=LGT), intent(in) :: lclose
real(kind=DP), intent(in) :: t
integer(kind=I4B), intent(inout) :: ireci
integer(kind=I4B), intent(inout) :: npl
integer(kind=I4B), intent(inout) :: nplm
integer(kind=I4B), intent(inout) :: ntp
type(symba_pl), intent(inout) :: symba_plA
type(symba_tp), intent(inout) :: symba_tpA
real(kind=DP), intent(in) :: dt0
real(kind=DP), intent(inout) :: eoffset
integer(kind=I4B), intent(inout) :: nplplenc
integer(kind=I4B), intent(inout) :: npltpenc
type(symba_plplenc), intent(inout) :: plplenc_list
type(symba_pltpenc), intent(inout) :: pltpenc_list
integer(kind=I4B), intent(inout) :: nmergeadd
integer(kind=I4B), intent(inout) :: nmergesub
type(symba_merger), intent(inout) :: mergeadd_list
type(symba_merger), intent(inout) :: mergesub_list
character(len=*), intent(in) :: encounter_file
character(len=*), intent(in) :: out_type
integer(kind=I4B), intent(inout) :: nplmax
integer(kind=I4B), intent(inout) :: ntpmax
integer(kind=I4B), intent(inout) :: fragmax
type(feature_list), intent(in) :: feature
Calls
Contents
None
Call graph
symba_step_recur calls symba_kick, symba_merge_pl, symba_fragmentation, symba_merge_tp, symba_helio_drift