symba_collision_casemerge – swiftest
symba_collision_casemerge Module Function
Jennifer L.L. Pouplin, Carlisle A. Wishard, and David A. Minton
57 statements
Source File
module function symba_collision_casemerge(system, param, colliders, frag) result(status) Interface →
Merge massive bodies.
Adapted from David E. Kaufmann's Swifter routines symba_merge_pl.f90 and symba_discard_merge_pl.f90
Adapted from Hal Levison's Swift routines symba5_merge.f and discard_mass_merge.f
Arguments
Type Intent Optional Attributes Name
class(symba_nbody_system), intent(inout) :: system
SyMBA nbody system object
class(symba_parameters), intent(inout) :: param
Current run configuration parameters with SyMBA additions
class(fraggle_colliders), intent(inout) :: colliders
Fraggle colliders object
class(fraggle_fragments), intent(inout) :: frag
Fraggle fragmentation system object
Return Value integer(kind=I4B)
Status flag assigned to this outcome
Calls
Called by
Contents
None
Call graph
symba_collision_casemerge calls symba_collision_collider_message, symba_collision_mergeaddsub, fraggle_io_log_one_message, symba_collision_casemerge
symba_collision_mergeaddsub calls fraggle_io_log_pl
symba_collision_resolve_mergers calls symba_collision_casemerge, symba_collision_resolve_mergers
symba_collision_resolve_fragmentations calls symba_collision_casemerge, symba_collision_resolve_fragmentations