symba_util_append_pl – swiftest
symba_util_append_pl Module Subroutine
David A. Minton
28 statements
Source File
module subroutine symba_util_append_pl(self, source, lsource_mask) Interface →
Append components from one massive body object to another. This method will automatically resize the destination body if it is too small Arguments
Arguments
Type Intent Optional Attributes Name
class(symba_pl), intent(inout) :: self
SyMBA massive body object
class(swiftest_body), intent(in) :: source
Source object to append
logical, intent(in), dimension(:) :: lsource_mask
Logical mask indicating which elements to append to
Calls
Called by
Contents
None
Call graph
symba_util_append_pl calls util_append, util_exit, util_append_pl, symba_util_append_pl
symba_util_append_merger calls symba_util_append_pl, symba_util_append_merger