symba_setup_initialize_system – swiftest
symba_setup_initialize_system Module Subroutine
David A. Minton
26 statements
Source File
module subroutine symba_setup_initialize_system(self, param) Interface →
Initialize an SyMBA nbody system from files and sets up the planetocentric structures. This subroutine will also sort the massive bodies in descending order by mass
Arguments
Type Intent Optional Attributes Name
class(symba_nbody_system), intent(inout) :: self
SyMBA system object
class(swiftest_parameters), intent(inout) :: param
Current run configuration parameters
Calls
Called by
Contents
None
Call graph
symba_setup_initialize_system calls symba_setup_initialize_particle_info, whm_setup_initialize_system, symba_io_read_particle, symba_setup_initialize_system
symba_setup_initialize_particle_info calls symba_setup_initialize_particle_info, symba_io_dump_particle_info
symba_io_read_particle calls symba_io_read_particle, util_exit
symba_io_dump_particle_info calls symba_io_dump_particle_info, util_exit