upper_triangle – swiftest
upper_triangle Function
10 statements
Source File
public function upper_triangle(j, k, extra)
Arguments
Type Intent Optional Attributes Name
integer(kind=I4B), intent(in) :: j
integer(kind=I4B), intent(in) :: k
integer(kind=I4B), intent(in), optional :: extra
Return Value logical(kind=LGT), DIMENSION(j, k)
Calls
Contents
None
Call graph
upper_triangle calls arth_i, outerdiff
outerdiff calls outerdiff_i, outerdiff_d