util_append_tp – swiftest
util_append_tp Module Subroutine
David A. Minton
19 statements
Source File
module subroutine util_append_tp(self, source, lsource_mask) Interface →
Append components from one Swiftest body object to another. This method will automatically resize the destination body if it is too small
Arguments
Type Intent Optional Attributes Name
class(swiftest_tp), intent(inout) :: self
Swiftest test particle object
class(swiftest_body), intent(in) :: source
Source object to append
logical, intent(in), dimension(:) :: lsource_mask
Logical mask indicating which elements to append to
Calls
Called by
Contents
None
Call graph
util_append_tp calls util_append, util_exit, util_append_body, util_append_tp
util_exit calls util_exit
util_append_body calls util_append_body, util_append