util_resize_pl – swiftest
util_resize_pl Subroutine
73 statements
Source File
subroutine util_resize_pl(symba_plA, npl_new, npl_old)
Uses
module_parameters
module_symba
module_swiftest
module_helio
module_nrutil
module_swiftestalloc
module_interfaces
Arguments
Type Intent Optional Attributes Name
type(symba_pl), intent(inout) :: symba_plA
integer(kind=I4B), intent(in) :: npl_new
integer(kind=I4B), intent(in) :: npl_old
Calls
Contents
None
Call graph
util_resize_pl calls symba_pl_allocate, symba_pl_deallocate
symba_pl_allocate calls helio_pl_allocate
symba_pl_deallocate calls helio_pl_deallocate
helio_pl_allocate calls swiftest_pl_allocate
helio_pl_deallocate calls swiftest_pl_deallocate