util_index – swiftest
util_index Subroutine
95 statements
Source File
subroutine util_index(arr, index)
Uses
module_parameters
module_nrutil
module_interfaces
Arguments
Type Intent Optional Attributes Name
real(kind=DP), intent(in), DIMENSION(:) :: arr
integer(kind=I4B), intent(out), DIMENSION(:) :: index
Calls
Contents
None
Call graph
util_index calls arth, util_exit
arth calls arth_d, arth_i