util_exit – swiftest
util_exit Module Subroutine
David A. Minton
19 statements
Source File
module subroutine util_exit(code) Interface →
Print termination message and exit program
Adapted from David E. Kaufmann's Swifter routine: util_exit.f90 Adapted from Hal Levison's Swift routine util_exit.f
Arguments
Type Intent Optional Attributes Name
integer(kind=I4B), intent(in) :: code
Called by
Contents
None
Call graph
util_exit calls util_exit
io_write_encounter calls util_exit, io_write_encounter
io_read_in_cb calls util_exit, io_read_in_cb
util_append_pl calls util_exit, util_append_pl
util_append_tp calls util_exit, util_append_tp
io_read_encounter calls util_exit
setup_construct_system calls util_exit, setup_construct_system
io_read_particle_info_system calls util_exit, io_read_particle_info_system
check calls util_exit
io_write_discard calls util_exit, io_write_discard
io_dump_particle_info_base calls util_exit, io_dump_particle_info_base
io_dump_particle_info calls util_exit, io_dump_particle_info
io_dump_param calls util_exit, io_dump_param
io_write_frame_encounter calls util_exit, io_write_frame_encounter
io_conservation_report calls util_exit, io_conservation_report
io_read_frame_cb calls util_exit, io_read_frame_cb
io_read_in_particle_info calls util_exit, io_read_in_particle_info
io_get_old_t_final_system calls util_exit, io_get_old_t_final_system
io_dump_base calls util_exit, io_write_frame_body, io_write_frame_cb, io_dump_base
io_write_hdr_system calls util_exit, io_write_hdr_system
io_read_in_param calls util_exit, io_read_in_param
util_solve_rkf45 calls util_exit, util_solve_rkf45
io_read_frame_body calls util_exit, io_read_frame_body
io_write_frame_body calls util_exit, io_write_frame_body
util_valid_id_system calls util_exit, util_valid_id_system
io_write_frame_cb calls util_exit, io_write_frame_cb
io_write_frame_system calls util_exit, io_write_frame_system
io_get_args calls util_exit, io_get_args