whm_coord_j2h_pl – swiftest
whm_coord_j2h_pl Module Subroutine
David A. Minton
21 statements
Source File
module subroutine whm_coord_j2h_pl(self, cb) Interface →
Convert from Jacobi to heliocentric coordinates, massive bodies only.
Uses pre-computed eta rather than computing it each time
Adapted from David E. Kaufmann's Swifter routine coord_j2h.f90
Adapted from Hal Levison's Swift routine coord_j2h.f
Arguments
Type Intent Optional Attributes Name
class(whm_pl), intent(inout) :: self
WHM massive body particle data structure
class(swiftest_cb), intent(inout) :: cb
Swiftest central body particle data structuree
Calls
Called by
Contents
None
Call graph
whm_coord_j2h_pl calls gmpl, vj, xj, vh, eta, xh, whm_coord_j2h_pl