fraggle_util_shift_vector_to_origin – swiftest
fraggle_util_shift_vector_to_origin Interface
157 statements
Source File
interface
Calls
Called by
public module subroutine fraggle_util_shift_vector_to_origin(m_frag, vec_frag) Implementation →
Arguments
Type Intent Optional Attributes Name
real(kind=DP), intent(in), dimension(:) :: m_frag
Fragment masses
real(kind=DP), intent(inout), dimension(:,:) :: vec_frag
Fragment positions or velocities in the center of mass frame
Call graph
fraggle_util_shift_vector_to_origin calls fraggle_util_shift_vector_to_origin
fraggle_util_vmag_to_vb calls fraggle_util_shift_vector_to_origin, fraggle_util_vmag_to_vb
fraggle_generate_pos_vec calls fraggle_util_shift_vector_to_origin
fraggle_generate_fragments calls fraggle_generate_pos_vec, fraggle_generate_tan_vel, fraggle_generate_rad_vel, fraggle_generate_fragments
fraggle_generate_tan_vel calls fraggle_util_vmag_to_vb
fraggle_generate_rad_vel calls fraggle_util_vmag_to_vb