io_get_args – swiftest
io_get_args Interface
368 statements
Source File
interface
Calls
public module function io_get_args(integrator, param_file_name) result(ierr) Implementation →
Arguments
Type Intent Optional Attributes Name
integer(kind=I4B) :: integrator
Symbolic code of the requested integrator
character(len=:), allocatable :: param_file_name
Name of the input parameters file
Return Value integer(kind=I4B)
I/O error code
Call graph
io_get_args calls io_get_args, util_version, util_exit, io_toupper
util_version calls util_version
util_exit calls util_exit
io_toupper calls io_toupper