io_open – swiftest
io_open Interface
9 statements
Source File
interface
Called by
public subroutine io_open(iu, fname, fopenstat, fmt, ierr)
Arguments
Type Intent Optional Attributes Name
integer(kind=I4B), intent(in) :: iu
character(len=*), intent(in) :: fname
character(len=*), intent(in) :: fopenstat
character(len=*), intent(in) :: fmt
integer(kind=I4B), intent(out) :: ierr
Call graph
io_getn calls io_open
io_write_frame calls io_open
io_read_encounter calls io_open
io_init_pl calls io_open
io_init_tp calls io_open
python_io_write_frame_tp calls io_open
io_discard_write_symba calls io_open
python_io_write_frame_pl calls io_open
io_write_encounter calls io_open