io_write_frame_system – swiftest
io_write_frame_system Interface
366 statements
Source File
interface
Calls
public module subroutine io_write_frame_system(self, iu, param) Implementation →
Arguments
Type Intent Optional Attributes Name
class(swiftest_nbody_system), intent(in) :: self
Swiftest system object
integer(kind=I4B), intent(inout) :: iu
Unit number for the output file to write frame to
class(swiftest_parameters), intent(in) :: param
Current run configuration parameters
Call graph
io_write_frame_system calls io_write_frame_system, util_exit, io_write_hdr
util_exit calls util_exit
io_write_hdr calls util_exit