ixdrclose – swiftest
ixdrclose Interface
6 statements
Source File
interface
Called by
public function ixdrclose(ixdr)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ixdr
Return Value integer
Call graph
io_init_pl calls ixdrclose
io_write_frame calls ixdrclose
io_getn calls ixdrclose
io_dump_pl calls ixdrclose
io_write_encounter calls ixdrclose
io_dump_tp calls ixdrclose
io_read_encounter calls ixdrclose
io_init_tp calls ixdrclose