orbel_xv2aeq – swiftest
orbel_xv2aeq Interface
9 statements
Source File
interface
Called by
public subroutine orbel_xv2aeq(x, v, mu, a, e, q)
Arguments
Type Intent Optional Attributes Name
real(kind=DP), intent(in), DIMENSION(NDIM) :: x
real(kind=DP), intent(in), DIMENSION(NDIM) :: v
real(kind=DP), intent(in) :: mu
real(kind=DP), intent(out) :: a
real(kind=DP), intent(out) :: e
real(kind=DP), intent(out) :: q
Call graph
symba_peri calls orbel_xv2aeq
symba_casesupercatastrophic calls orbel_xv2aeq
util_peri calls orbel_xv2aeq
symba_casedisruption calls orbel_xv2aeq