rmvs_chk_ind – swiftest
rmvs_chk_ind Interface
134 statements
Source File
interface
Calls
Called by
public elemental module function rmvs_chk_ind(r2, v2, vdotr, dt, r2crit) result(lflag) Implementation →
Arguments
Type Intent Optional Attributes Name
real(kind=DP), intent(in) :: r2
real(kind=DP), intent(in) :: v2
real(kind=DP), intent(in) :: vdotr
real(kind=DP), intent(in) :: dt
real(kind=DP), intent(in) :: r2crit
Return Value logical
Call graph
rmvs_chk_ind calls rmvs_chk_ind
rmvs_encounter_check_tp calls rmvs_chk_ind, rmvs_encounter_check_tp
symba_encounter_check_one calls rmvs_chk_ind, symba_encounter_check_one