setup_body – swiftest
setup_body Interface
465 statements
Source File
interface
Calls
Called by
public module subroutine setup_body(self, n, param) Implementation →
Arguments
Type Intent Optional Attributes Name
class(swiftest_body), intent(inout) :: self
Swiftest body object
integer(kind=I4B), intent(in) :: n
Number of particles to allocate space for
class(swiftest_parameters), intent(in) :: param
Current run configuration parameters
Call graph
setup_body calls setup_body
setup_pl calls setup_body, setup_pl
setup_tp calls setup_body, setup_tp