symba_util_resize_pl – swiftest
symba_util_resize_pl Interface
39 statements
Source File
interface
Calls
Called by
public module subroutine symba_util_resize_pl(self, nnew) Implementation →
Arguments
Type Intent Optional Attributes Name
class(symba_pl), intent(inout) :: self
SyMBA massive body object
integer(kind=I4B), intent(in) :: nnew
New size neded
Call graph
symba_util_resize_pl calls symba_util_resize_pl, util_resize_pl, util_resize
symba_util_resize_merger calls symba_util_resize_pl, symba_util_resize_merger