symba_util_spill_encounter – swiftest
symba_util_spill_encounter Interface
26 statements
Source File
interface
Calls
public module subroutine symba_util_spill_encounter(self, discards, lspill_list, ldestructive) Implementation →
Arguments
Type Intent Optional Attributes Name
class(symba_encounter), intent(inout) :: self
SyMBA pl-tp encounter list
class(swiftest_encounter), intent(inout) :: discards
Discarded object
logical, intent(in), dimension(:) :: lspill_list
Logical array of bodies to spill into the discards
logical, intent(in) :: ldestructive
Logical flag indicating whether or not this operation should alter body by removing the discard list
Call graph
symba_util_spill_encounter calls symba_util_spill_encounter, util_exit, util_spill, util_spill_encounter