symba_collision_check_pltpenc – swiftest
symba_collision_check_pltpenc Interface
264 statements
Source File
interface
Calls
public module subroutine symba_collision_check_pltpenc(self, system, param, t, dt, irec) Implementation →
Arguments
Type Intent Optional Attributes Name
class(symba_pltpenc), intent(inout) :: self
SyMBA pl-tp encounter list object
class(symba_nbody_system), intent(inout) :: system
SyMBA nbody system object
class(swiftest_parameters), intent(in) :: param
Current run configuration parameters
real(kind=DP), intent(in) :: t
current time
real(kind=DP), intent(in) :: dt
step size
integer(kind=I4B), intent(in) :: irec
Current recursion level
Call graph
symba_collision_check_pltpenc calls symba_collision_check_pltpenc, ind1, symba_collision_check_one, ind2
symba_collision_check_one calls orbel_xv2aeq