symba_fragmentation_casemerge – swiftest
symba_fragmentation_casemerge Interface
264 statements
Source File
interface
Calls
Called by
public module function symba_fragmentation_casemerge(system, param, family, x, v, mass, radius, L_spin, Ip) result(status) Implementation →
Arguments
Type Intent Optional Attributes Name
class(symba_nbody_system), intent(inout) :: system
SyMBA nbody system object
class(symba_parameters), intent(in) :: param
Current run configuration parameters with SyMBA additions
integer(kind=I4B), intent(in), dimension(:) :: family
List of indices of all bodies inovlved in the collision
real(kind=DP), intent(in), dimension(:,:) :: x
Input values that represent a 2-body equivalent of a possibly 2+ body collision
real(kind=DP), intent(in), dimension(:,:) :: v
Input values that represent a 2-body equivalent of a possibly 2+ body collision
real(kind=DP), intent(in), dimension(:) :: mass
Input values that represent a 2-body equivalent of a possibly 2+ body collisio
real(kind=DP), intent(in), dimension(:) :: radius
Input values that represent a 2-body equivalent of a possibly 2+ body collisio
real(kind=DP), intent(in), dimension(:,:) :: L_spin
Input values that represent a 2-body equivalent of a possibly 2+ body collision
real(kind=DP), intent(in), dimension(:,:) :: Ip
Input values that represent a 2-body equivalent of a possibly 2+ body collision
Return Value integer(kind=I4B)
Status flag assigned to this outcome
Call graph
symba_fragmentation_casemerge calls symba_fragmentation_casemerge, symba_fragmentation_mergeaddsub
symba_collision_resolve_mergers calls symba_fragmentation_casemerge, symba_collision_resolve_mergers
symba_collision_resolve_fragmentations calls symba_fragmentation_casemerge, symba_collision_resolve_fragmentations