symba_setup_initialize_particle_info – swiftest
symba_setup_initialize_particle_info Interface
264 statements
Source File
interface
Calls
Called by
public module subroutine symba_setup_initialize_particle_info(system, param) Implementation →
Arguments
Type Intent Optional Attributes Name
class(symba_nbody_system), intent(inout) :: system
SyMBA nbody system object
class(symba_parameters), intent(inout) :: param
Current run configuration parameters with SyMBA extensions
Call graph
symba_setup_initialize_particle_info calls symba_setup_initialize_particle_info, symba_io_dump_particle_info
symba_io_dump_particle_info calls symba_io_dump_particle_info, util_exit
symba_setup_initialize_system calls symba_setup_initialize_particle_info, symba_setup_initialize_system