symba_collision_casedisruption – swiftest
symba_collision_casedisruption Interface
261 statements
Source File
interface
Calls
Called by
public module function symba_collision_casedisruption(system, param, colliders, frag) result(status) Implementation →
Arguments
Type Intent Optional Attributes Name
class(symba_nbody_system), intent(inout) :: system
SyMBA nbody system object
class(symba_parameters), intent(inout) :: param
Current run configuration parameters with SyMBA additions
class(fraggle_colliders), intent(inout) :: colliders
Fraggle colliders object
class(fraggle_fragments), intent(inout) :: frag
Fraggle fragmentation system object
Return Value integer(kind=I4B)
Status flag assigned to this outcome
Call graph
symba_collision_casedisruption calls symba_collision_casedisruption, symba_collision_collider_message, symba_collision_mergeaddsub, fraggle_io_log_one_message
symba_collision_mergeaddsub calls fraggle_io_log_pl
symba_collision_resolve_fragmentations calls symba_collision_casedisruption, symba_collision_resolve_fragmentations