symba_encounter_check_pltpenc – swiftest
symba_encounter_check_pltpenc Interface
264 statements
Source File
interface
Calls
public module function symba_encounter_check_pltpenc(self, system, dt, irec) result(lany_encounter) Implementation →
Arguments
Type Intent Optional Attributes Name
class(symba_pltpenc), intent(inout) :: self
SyMBA pl-pl encounter list object
class(symba_nbody_system), intent(inout) :: system
SyMBA nbody system object
real(kind=DP), intent(in) :: dt
step size
integer(kind=I4B), intent(in) :: irec
Current recursion level
Return Value logical
Returns true if there is at least one close encounter
Call graph
symba_encounter_check_pltpenc calls symba_encounter_check_pltpenc, ind1, ind2