util_coord_b2h_pl – swiftest
util_coord_b2h_pl Interface
67 statements
Source File
interface
Calls
public module subroutine util_coord_b2h_pl(self, cb) Implementation →
Arguments
Type Intent Optional Attributes Name
class(swiftest_pl), intent(inout) :: self
Swiftest massive body object
class(swiftest_cb), intent(inout) :: cb
Swiftest central body object
Call graph
util_coord_b2h_pl calls util_coord_b2h_pl, vbcb, xh, xb, xbcb, vh, vb