util_sort_rearrange – swiftest
util_sort_rearrange Interface
38 statements
Source File
public interface util_sort_rearrange
Called by
Contents
Subroutines
util_sort_rearrange_arr_char_string util_sort_rearrange_arr_DP util_sort_rearrange_arr_DPvec util_sort_rearrange_arr_I4B util_sort_rearrange_arr_info util_sort_rearrange_arr_logical
Subroutines
public subroutine util_sort_rearrange_arr_char_string(arr, ind, n)
Arguments
Type Intent Optional Attributes Name
character(len=STRMAX), intent(inout), dimension(:), allocatable :: arr
Destination array
integer(kind=I4B), intent(in), dimension(:) :: ind
Index to rearrange against
integer(kind=I4B), intent(in) :: n
Number of elements in arr and ind to rearrange
public subroutine util_sort_rearrange_arr_DP(arr, ind, n)
Arguments
Type Intent Optional Attributes Name
real(kind=DP), intent(inout), dimension(:), allocatable :: arr
Destination array
integer(kind=I4B), intent(in), dimension(:) :: ind
Index to rearrange against
integer(kind=I4B), intent(in) :: n
Number of elements in arr and ind to rearrange
public subroutine util_sort_rearrange_arr_DPvec(arr, ind, n)
Arguments
Type Intent Optional Attributes Name
real(kind=DP), intent(inout), dimension(:,:), allocatable :: arr
Destination array
integer(kind=I4B), intent(in), dimension(:) :: ind
Index to rearrange against
integer(kind=I4B), intent(in) :: n
Number of elements in arr and ind to rearrange
public subroutine util_sort_rearrange_arr_I4B(arr, ind, n)
Arguments
Type Intent Optional Attributes Name
integer(kind=I4B), intent(inout), dimension(:), allocatable :: arr
Destination array
integer(kind=I4B), intent(in), dimension(:) :: ind
Index to rearrange against
integer(kind=I4B), intent(in) :: n
Number of elements in arr and ind to rearrange
public subroutine util_sort_rearrange_arr_info(arr, ind, n)
Arguments
Type Intent Optional Attributes Name
type(swiftest_particle_info), intent(inout), dimension(:), allocatable :: arr
Destination array
integer(kind=I4B), intent(in), dimension(:) :: ind
Index to rearrange against
integer(kind=I4B), intent(in) :: n
Number of elements in arr and ind to rearrange
public subroutine util_sort_rearrange_arr_logical(arr, ind, n)
Arguments
Type Intent Optional Attributes Name
logical, intent(inout), dimension(:), allocatable :: arr
Destination array
integer(kind=I4B), intent(in), dimension(:) :: ind
Index to rearrange against
integer(kind=I4B), intent(in) :: n
Number of elements in arr and ind to rearrange
Call graph
util_sort_rearrange_body calls util_sort_rearrange, util_sort_rearrange_body
util_sort_rearrange_tp calls util_sort_rearrange, util_sort_rearrange_body, util_sort_rearrange_tp
util_sort_rearrange_pl calls util_sort_rearrange, util_sort_rearrange_body, util_sort_rearrange_pl