util_resize – swiftest
util_resize Interface
12 statements
Source File
public interface util_resize
Called by
Contents
Subroutines
symba_util_resize_arr_info symba_util_resize_arr_kin
Subroutines
public subroutine symba_util_resize_arr_info(arr, nnew)
Arguments
Type Intent Optional Attributes Name
type(symba_particle_info), intent(inout), dimension(:), allocatable :: arr
Array to resize
integer(kind=I4B), intent(in) :: nnew
New size
public subroutine symba_util_resize_arr_kin(arr, nnew)
Arguments
Type Intent Optional Attributes Name
type(symba_kinship), intent(inout), dimension(:), allocatable :: arr
Array to resize
integer(kind=I4B), intent(in) :: nnew
New size
Call graph
symba_util_append_arr_info calls util_resize
symba_util_resize_tp calls util_resize, symba_util_resize_tp
symba_util_resize_merger calls util_resize, symba_util_resize_pl, symba_util_resize_merger
symba_util_resize_pl calls util_resize, symba_util_resize_pl
symba_util_append_arr_kin calls util_resize