util_spill – swiftest
util_spill Interface
51 statements
Source File
public interface util_spill
Called by
Contents
Subroutines
util_spill_arr_char_string util_spill_arr_DP util_spill_arr_DPvec util_spill_arr_I4B util_spill_arr_I8B util_spill_arr_info util_spill_arr_logical
Subroutines
public subroutine util_spill_arr_char_string(keeps, discards, lspill_list, ldestructive)
Arguments
Type Intent Optional Attributes Name
character(len=STRMAX), intent(inout), dimension(:), allocatable :: keeps
Array of values to keep
character(len=STRMAX), intent(inout), dimension(:), allocatable :: discards
Array of discards
logical, intent(in), dimension(:) :: lspill_list
Logical array of bodies to spill into the discardss
logical, intent(in) :: ldestructive
Logical flag indicating whether or not this operation should alter the keeps array or not
public subroutine util_spill_arr_DP(keeps, discards, lspill_list, ldestructive)
Arguments
Type Intent Optional Attributes Name
real(kind=DP), intent(inout), dimension(:), allocatable :: keeps
Array of values to keep
real(kind=DP), intent(inout), dimension(:), allocatable :: discards
Array of discards
logical, intent(in), dimension(:) :: lspill_list
Logical array of bodies to spill into the discards
logical, intent(in) :: ldestructive
Logical flag indicating whether or not this operation should alter the keeps array or not
public subroutine util_spill_arr_DPvec(keeps, discards, lspill_list, ldestructive)
Arguments
Type Intent Optional Attributes Name
real(kind=DP), intent(inout), dimension(:,:), allocatable :: keeps
Array of values to keep
real(kind=DP), intent(inout), dimension(:,:), allocatable :: discards
Array discards
logical, intent(in), dimension(:) :: lspill_list
Logical array of bodies to spill into the discards
logical, intent(in) :: ldestructive
Logical flag indicating whether or not this operation should alter the keeps array or not
public subroutine util_spill_arr_I4B(keeps, discards, lspill_list, ldestructive)
Arguments
Type Intent Optional Attributes Name
integer(kind=I4B), intent(inout), dimension(:), allocatable :: keeps
Array of values to keep
integer(kind=I4B), intent(inout), dimension(:), allocatable :: discards
Array of discards
logical, intent(in), dimension(:) :: lspill_list
Logical array of bodies to spill into the discardss
logical, intent(in) :: ldestructive
Logical flag indicating whether or not this operation should alter the keeps array or not
public subroutine util_spill_arr_I8B(keeps, discards, lspill_list, ldestructive)
Arguments
Type Intent Optional Attributes Name
integer(kind=I8B), intent(inout), dimension(:), allocatable :: keeps
Array of values to keep
integer(kind=I8B), intent(inout), dimension(:), allocatable :: discards
Array of discards
logical, intent(in), dimension(:) :: lspill_list
Logical array of bodies to spill into the discardss
logical, intent(in) :: ldestructive
Logical flag indicating whether or not this operation should alter the keeps array or not
public subroutine util_spill_arr_info(keeps, discards, lspill_list, ldestructive)
Arguments
Type Intent Optional Attributes Name
type(swiftest_particle_info), intent(inout), dimension(:), allocatable :: keeps
Array of values to keep
type(swiftest_particle_info), intent(inout), dimension(:), allocatable :: discards
Array of discards
logical, intent(in), dimension(:) :: lspill_list
Logical array of bodies to spill into the discardss
logical, intent(in) :: ldestructive
Logical flag indicating whether or not this operation should alter the keeps array or not
public subroutine util_spill_arr_logical(keeps, discards, lspill_list, ldestructive)
Arguments
Type Intent Optional Attributes Name
logical, intent(inout), dimension(:), allocatable :: keeps
Array of values to keep
logical, intent(inout), dimension(:), allocatable :: discards
Array of discards
logical, intent(in), dimension(:) :: lspill_list
Logical array of bodies to spill into the discardss
logical, intent(in) :: ldestructive
Logical flag indicating whether or not this operation should alter the keeps array or not
Call graph
util_spill_encounter calls util_spill, util_spill_encounter
util_spill_body calls util_spill, util_spill_body
util_spill_pl calls util_spill, util_spill_body, util_spill_pl
util_spill_tp calls util_spill, util_spill_body, util_spill_tp