util_append – swiftest
util_append Interface
9 statements
Source File
public interface util_append
Called by
Contents
Subroutines
symba_util_append_arr_kin
Subroutines
public subroutine symba_util_append_arr_kin(arr, source, nold, nsrc, lsource_mask)
Arguments
Type Intent Optional Attributes Name
type(symba_kinship), intent(inout), dimension(:), allocatable :: arr
Destination array
type(symba_kinship), intent(in), dimension(:), allocatable :: source
Array to append
integer(kind=I4B), intent(in) :: nold
Extend of the old array and the source array, respectively
integer(kind=I4B), intent(in) :: nsrc
Extend of the old array and the source array, respectively
logical, intent(in), dimension(:) :: lsource_mask
Logical mask indicating which elements to append to
Call graph
symba_util_append_encounter calls util_append, symba_util_append_encounter
symba_util_append_pl calls util_append, symba_util_append_pl
symba_util_append_tp calls util_append, symba_util_append_tp
symba_util_append_merger calls util_append, symba_util_append_pl, symba_util_append_merger