util_append – swiftest
util_append Interface
32 statements
Source File
public interface util_append
Called by
Contents
Subroutines
util_append_arr_char_string util_append_arr_DP util_append_arr_DPvec util_append_arr_I4B util_append_arr_logical
Subroutines
public subroutine util_append_arr_char_string(arr, source, lsource_mask)
Arguments
Type Intent Optional Attributes Name
character(len=STRMAX), intent(inout), dimension(:), allocatable :: arr
Destination array
character(len=STRMAX), intent(in), dimension(:), allocatable :: source
Array to append
logical, intent(in), optional dimension(:) :: lsource_mask
Logical mask indicating which elements to append to
public subroutine util_append_arr_DP(arr, source, lsource_mask)
Arguments
Type Intent Optional Attributes Name
real(kind=DP), intent(inout), dimension(:), allocatable :: arr
Destination array
real(kind=DP), intent(in), dimension(:), allocatable :: source
Array to append
logical, intent(in), optional dimension(:) :: lsource_mask
Logical mask indicating which elements to append to
public subroutine util_append_arr_DPvec(arr, source, lsource_mask)
Arguments
Type Intent Optional Attributes Name
real(kind=DP), intent(inout), dimension(:,:), allocatable :: arr
Destination array
real(kind=DP), intent(in), dimension(:,:), allocatable :: source
Array to append
logical, intent(in), optional dimension(:) :: lsource_mask
Logical mask indicating which elements to append to
public subroutine util_append_arr_I4B(arr, source, lsource_mask)
Arguments
Type Intent Optional Attributes Name
integer(kind=I4B), intent(inout), dimension(:), allocatable :: arr
Destination array
integer(kind=I4B), intent(in), dimension(:), allocatable :: source
Array to append
logical, intent(in), optional dimension(:) :: lsource_mask
Logical mask indicating which elements to append to
public subroutine util_append_arr_logical(arr, source, lsource_mask)
Arguments
Type Intent Optional Attributes Name
logical, intent(inout), dimension(:), allocatable :: arr
Destination array
logical, intent(in), dimension(:), allocatable :: source
Array to append
logical, intent(in), optional dimension(:) :: lsource_mask
Logical mask indicating which elements to append to
Call graph
util_append_tp calls util_append, util_append_body, util_append_tp
util_append_body calls util_append, util_append_body
util_append_pl calls util_append, util_append_body, util_append_pl