util_resize – swiftest
util_resize Interface
32 statements
Source File
public interface util_resize
Called by
Contents
Subroutines
util_resize_arr_char_string util_resize_arr_DP util_resize_arr_DPvec util_resize_arr_I4B util_resize_arr_info util_resize_arr_logical
Subroutines
public subroutine util_resize_arr_char_string(arr, nnew)
Arguments
Type Intent Optional Attributes Name
character(len=STRMAX), intent(inout), dimension(:), allocatable :: arr
Array to resize
integer(kind=I4B), intent(in) :: nnew
New size
public subroutine util_resize_arr_DP(arr, nnew)
Arguments
Type Intent Optional Attributes Name
real(kind=DP), intent(inout), dimension(:), allocatable :: arr
Array to resize
integer(kind=I4B), intent(in) :: nnew
New size
public subroutine util_resize_arr_DPvec(arr, nnew)
Arguments
Type Intent Optional Attributes Name
real(kind=DP), intent(inout), dimension(:,:), allocatable :: arr
Array to resize
integer(kind=I4B), intent(in) :: nnew
New size
public subroutine util_resize_arr_I4B(arr, nnew)
Arguments
Type Intent Optional Attributes Name
integer(kind=I4B), intent(inout), dimension(:), allocatable :: arr
Array to resize
integer(kind=I4B), intent(in) :: nnew
New size
public subroutine util_resize_arr_info(arr, nnew)
Arguments
Type Intent Optional Attributes Name
type(swiftest_particle_info), intent(inout), dimension(:), allocatable :: arr
Array to resize
integer(kind=I4B), intent(in) :: nnew
New size
public subroutine util_resize_arr_logical(arr, nnew)
Arguments
Type Intent Optional Attributes Name
logical, intent(inout), dimension(:), allocatable :: arr
Array to resize
integer(kind=I4B), intent(in) :: nnew
New size
Call graph
util_append_arr_char_string calls util_resize
util_resize_body calls util_resize, util_resize_body
util_resize_pl calls util_resize, util_resize_body, util_resize_pl
util_append_arr_i4b calls util_resize
util_append_arr_dp calls util_resize
util_append_arr_dpvec calls util_resize
util_append_arr_logical calls util_resize
util_resize_tp calls util_resize, util_resize_body, util_resize_tp
util_append_arr_info calls util_resize