name: deploy_swiftest

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  call-build_wheels:
    uses: ./.github/workflows/build_wheels.yml@main
    secrets: inherit

  download_artifacts:
    needs: [call-build_wheels]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} 
          run_id: ${{ github.run_id}}
          pattern: cibw-*
          path: wheelhouse
          merge-multiple: true

  upload_pypi:
    needs: [download_artifacts]
    runs-on: ubuntu-latest
    environment: 
      name: pypi
      url: https://pypi.org/p/swiftest
    permissions:
      id-token: write
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
